### ISSUE TITLE
http headers cause Font Awesome to not work on IE8 over https

### ISSUE THREAD

**Issue by jonwolfe** [MaxCDN/bootstrap-cdn#326]
We're loading font awesome via a protocol-less url (//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css)

The icons work on all the browsers we need to support, except IE8 over https. IE8 over http is fine.

Did some searching, and the culprit seems like it could be the http cache headers: http://stackoverflow.com/a/22693512

**Comment by jdorfman** [comment]
We now recommend not using protocol-less urls in favor of `https:`.
