### ISSUE TITLE
Update tests to include content-type tests for font files.

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#346]

**Comment by jmervine** [comment]
@jdorfman I started working on this, hoping to finish over the long weekend. With the addition of the new integration suite, this will do nicely to round things out. I'm guessing we're going to find a lot of errors when we push this at first. I can try to whip something together that programmatically goes though and adjusts the content types in s3 if it's too many, otherwise you or I can just quickly adjust them manually.

**Comment by jmervine** [comment]
FYI, here's the mapping I'm using:

```javascript
var expectedMimeTypes = {
    css: 'text/css',
    js:  'application/x-javascript',

    // fonts
    eot:   'application/vnd.ms-fontobject',
    svg:   'image/svg+xml',
    ttf:   'application/x-font-ttf',
    woff:  'application/font-woff',
    woff2: 'application/font-woff2',
    otf:   'application/x-font-otf'
};
```

**Comment by jdorfman** [comment]
> I'm guessing we're going to find a lot of errors when we push this at first. 

You are guessing right.  I have noticed some of the woff2's mime types are `application/octet-stream` So this is a good thing.  

FYI here is a breakdown of the most popular file types:

![image](https://cloud.githubusercontent.com/assets/398230/11403199/7350e2d4-9350-11e5-853a-91057b8f9898.png)

**Comment by jmervine** [comment]
That's helpful for sure. Think I should find and add the `png` and `ico` files? My guess is they're more static. So it might not be necessary.

Also, should I pass a specific header when requesting these endpoints testing, so we can filter them out from the metrics?

**Comment by jdorfman** [comment]
> Think I should find and add the png and ico files?

No need. As you said, not necessary

> Also, should I pass a specific header when requesting these endpoints testing, so we can filter them out from the metrics?

Not necessary, testing vs production traffic is like a needle in 43 billion stacks of hay.

**Comment by jdorfman** [comment]
great job @jmervine
