### ISSUE TITLE
Use bootlint correctly in testing...

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#487]
See #484.

**Comment by XhmikosR** [comment]
I also believe the validator doesn't run right either; it runs only for one page and not for all the pages...

**Comment by jdorfman** [comment]
can this be closed?

**Comment by jmervine** [comment]
Nah, this should be reviewed and fixed eventually. In fact I'd like to do a serious overhaul on testing in general. Let's leave it open as a reminder for now.

**Comment by jdorfman** [comment]
word, thanks for the clarification =)

**Comment by jdorfman** [comment]
@jmervine did #598 fix this?

**Comment by jmervine** [comment]
Yes.

**Comment by jdorfman** [comment]
:smile:
