### ISSUE TITLE
Add DNS Prefetch example to Docs

### ISSUE THREAD

**Issue by bhubbard** [MaxCDN/bootstrap-cdn#492]
I have used DNS Prefetch for several projects that use bootstrapcdn. I think it would be great to show an example of this for users:

```<link rel="dns-prefetch" href="//maxcdn.bootstrapcdn.com">```

**Comment by XhmikosR** [comment]
IMO this doesn't belong here. It's a technique that belongs to HTML5 Boilerplate for instance, which already has this info.

**Comment by jmervine** [comment]
@bhubbard I appreciate the thought, for sure. However, I tend to agree with @XhmikosR that this is not the correct place for this.

Cheers!
J
