### ISSUE TITLE
add Bootlint v0.10.0

### ISSUE THREAD

**Issue by cvrebert** [MaxCDN/bootstrap-cdn#497]
Thanks as always!
https://github.com/twbs/bootlint/releases/tag/v0.10.0

**Comment by jdorfman** [comment]
On it thanks @cvrebert

**Comment by jdorfman** [comment]
@cvrebert `bootlint.min.js` appears to be missing.  Should I just add the `bootlint.js` instead?

**Comment by cvrebert** [comment]
Upstream doesn't include a minified version since Bootlint is only for debugging and isn't perf-critical. Looks like y'all have been minifying it yourselves so far.
We need `bootlint/latest/bootlint.min.js` to exist due to the bookmarklet, but it's fine if that's not actually minified and it's fine if there's not any `bootlint/0.10.0/bootlint.min.js` file.

**Comment by jdorfman** [comment]
That is what I thought but didn't want to make a stupid assumption. I will get this up now.

**Comment by jmervine** [comment]
@jdorfman there's a script to create min @ `./scripts/update_bootlint.sh`.

Usage:

```bash
./scripts/update_bootlint.sh 0.10.0
```

**Comment by jdorfman** [comment]
sheet didn't see that.  I will use that next time.  Thanks @jmervine
