### ISSUE TITLE
Update "Mad Love" section.

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#503]
Ideally, this would be automated to use Twitter API and dynamically pull last "n" tweet with "#bootstrapcdn". Short of that, we should at very least (or perhaps in the mean time) update the list (here: https://github.com/MaxCDN/bootstrap-cdn/blob/develop/config/_love.yml) with some more recent tweets.

(cc/ @jdorfman)

**Comment by jdorfman** [comment]
The dynamic idea is good but I rather us moderate what goes up.

In the meantime I will have @jimaek pull some new tweets and update `_love.yml`

**Comment by jmervine** [comment]
+1 if we're gonna stay manual, we should update it regularly.

**Comment by jdorfman** [comment]
agreed

**Comment by jdorfman** [comment]
@jimaek is working on this today

**Comment by jimaek** [comment]
https://github.com/MaxCDN/bootstrap-cdn/pull/565

**Comment by jmervine** [comment]
#566 prod release
