### ISSUE TITLE
Font Awesome icons show up as rectangles on load, only appear on Ctrl-F5

### ISSUE THREAD

**Issue by Revarye** [MaxCDN/bootstrap-cdn#512]
I started encountering this issue some time after upgrading to Font Awesome 4.2.0, and can replicate it consistently on all the browsers I use.

Load (icons show up as rectangles):
![load](https://cloud.githubusercontent.com/assets/7857107/6409290/5cbdb35a-be9c-11e4-95a3-85903886d399.png)
Chrome is showing that the font file sizes are all 0? However, when I access their links directly in my browser, I'm able to download the files properly.

F5 doesn't cause the icons to render correctly, but Ctrl-F5 does:
![refresh](https://cloud.githubusercontent.com/assets/7857107/6409291/5cbdb58a-be9c-11e4-90fb-0e58e2eaf529.png)

Not sure if this is related, but I'm located in Singapore. I tried using Hotspot Shield (location set to US) and the icons show up correctly on first load. Could this be something related to the Asia CDN servers?

Edit:
My website is http://www.capsulecraft.com/shades (the icons are on the Lighter / Darker buttons).

**Comment by jimaek** [comment]
Please include the full HTTP headers for the requests in both cases.

**Comment by Revarye** [comment]
This is for the .woff2 request for a fresh load (rectangles):

Request
```
GET /font-awesome/4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1
Host: maxcdn.bootstrapcdn.com
Connection: keep-alive
Origin: http://www.capsulecraft.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Accept: */*
Referer: http://capsulecraft-cdn.appspot.com/css/shades.css
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Response
```
HTTP/1.1 200 OK
Content-Length: 56780
Content-Type: application/octet-stream
ETag: "97493d3f11c0a3bd5cbd959f5d19b699"
Server: NetDNA-cache/2.2
Expires: Mon, 22 Feb 2016 11:24:18 GMT
Last-Modified: Thu, 22 Jan 2015 19:53:46 GMT
Connection: keep-alive
Date: Fri, 27 Feb 2015 12:23:15 GMT
```

Headers after Ctrl-F5 refresh (icons rendered):

Request
```
GET /font-awesome/4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1
Host: maxcdn.bootstrapcdn.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Origin: http://www.capsulecraft.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Accept: */*
Referer: http://capsulecraft-cdn.appspot.com/css/shades.css
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Response
```
HTTP/1.1 200 OK
Date: Fri, 27 Feb 2015 12:35:46 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
Last-Modified: Thu, 22 Jan 2015 19:53:46 GMT
ETag: W/"97493d3f11c0a3bd5cbd959f5d19b699"
Server: NetDNA-cache/2.2
Expires: Mon, 22 Feb 2016 12:35:46 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: You should work for us! Email: jdorfman+theheader@maxcdn.com or @MaxCDNDeveloper on Twitter
X-Cache: HIT
Content-Encoding: gzip
```

**Comment by jmervine** [comment]
This is probably an issue with the content type. AWS S3 fails at setting the correct content types with some file types. I'll manually update `/font-awesome/4.3.0/fonts/fontawesome-webfont.woff2` and request a cache purge. Hopefully it will fix the issue.

**Comment by jmervine** [comment]
The content type has been updated. Please let me know if you're still experiencing this issue.

**Comment by Revarye** [comment]
Sorry, it hasn't fixed the issue. It may not be .woff2 in particular because it happens with .woff and .ttf as well (first screenshot).

**Comment by jmervine** [comment]
@Revarye Apologies, I should have noticed that.  I'll keep digging.

**Comment by Revarye** [comment]
@jmervine No worries, I appreciate all your help and effort :smiley_cat: thanks!

**Comment by jmervine** [comment]
@Revarye Hey, so I ran a webpagetest.org against your site from Singapore, using FF, and the issue doesn't seem to be appearing. Can you think of anything that might be specific about your setup that may be causing this for you alone? Are you seeing the issue in multiple browsers? 

Here's the WPT test run:

http://www.webpagetest.org/result/150228_Q6_46H/

LMK,
J

**Comment by Revarye** [comment]
>> Can you think of anything that might be specific about your setup that may be causing this for you alone?

Thank you for this! So my ISP provides a proxy server for us to configure our web clients, although I haven't used this proxy in years with no problems. I just changed my browsers to use it, and indeed - issue disappeared.

It seems if we don't use the above proxy, the ISP uses a transparent proxy, which may be where the problem lies. I'll contact them about this and hopefully they can fix it. Grateful for your time and kind help! :sparkles:

**Comment by jmervine** [comment]
Awesome, good that it's a local issue and your visitors shouldn't be troubled.

Cheers!
J
