### ISSUE TITLE
Add Flatstrap theme to CDN

### ISSUE THREAD

**Issue by FlareHAX0R** [MaxCDN/bootstrap-cdn#515]
http://flatstrap.org/

PLEASE add that to the CDN, minified!

**Comment by jmervine** [comment]
Based on previous discussions regarding adding Flatstrap with @jdorfman -- who is the descision maker as far as adding additional content here, and is also on hiatus at this time -- we've concluded that this is not the correct location for Flatstrap at this time, as it's Bootstrap focused.

**Comment by FlareHAX0R** [comment]
@jmervine I dont like hosting frameworks locally. And I really wanna use flatstrap.

**Comment by jmervine** [comment]
@FlareHAX0R I understand that, unfortunately I can't help you at this time.
