### ISSUE TITLE
Switch from "//" to "https://"?

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#530]
See: https://twitter.com/mathias/status/582805207270166528

**Comment by mathiasbynens** [comment]
I’m happy to submit a PR for this, so it’s easier to review.

**Comment by mathiasbynens** [comment]
Done: #531.

**Comment by jmervine** [comment]
@mathiasbynens Thanks for your contribution. I'm opening a dialog with @jdorfman and I'll get back to you on this soon.

**Comment by jdorfman** [comment]
@jmervine This should be merged after reading www.paulirish.com/2010/the-protocol-relative-url/

**Comment by jmervine** [comment]
Okay, I'm going to set aside some time to look at it. Need to get the tests passing. I'll probably not merge, but rather create an integration branch.
