### ISSUE TITLE
netdna.bootstrapcdn.com dont have ipv6

### ISSUE THREAD

**Issue by Pedro-Miguel** [MaxCDN/bootstrap-cdn#533]
Hi,

1st off all sorry if this issue dont belong here.

No one can use bootstrap served via netdna.bootstrapcdn.com on Ipv6.

**Comment by jdorfman** [comment]
Hey Pedro,

It is being worked on, we do not have an ETA as of now.  I will follow up once it is deployed.

**Comment by anthonysomerset** [comment]
Is there any update on this? also includes DNS record maxcdn.bootstrapcdn.com

**Comment by jdorfman** [comment]
@anthonysomerset I wish I could give you an update. There are higher priorities at the moment. Don't get me wrong IPv6 is important, it hasn't been an issue with current customers.

**Comment by gsauthof** [comment]
Can confirm, maxcdn.bootstrapcdn.com and oss.maxcdn.com still don't have AAAA records.

In contrast to that, e.g. ajax.googleapis.com has an AAAA record and works over IPv6.

**Comment by jdorfman** [comment]
@gsauthof you are correct, we still don't have `AAAA` records. I sent this to my contacts at MaxCDN/StackPath so it is on their radar.

**Comment by phillipremaker** [comment]
It's 2017 and still no IPv6. What's the progress and schedule?

**Comment by davecarlson** [comment]
AWS is IPv6 capable now - have you ensured it's enabled ?

For cloudfront, it's just a tickbox now !

<img width="715" alt="screen shot 2017-12-12 at 11 56 54" src="https://user-images.githubusercontent.com/299702/33883408-9538e64a-df33-11e7-9eda-b44530520d77.png">

**Comment by jdorfman** [comment]
@davecarlson we don't use Cloudfront, StackPath is our CDN provider. No ETA when they are getting IPv6 support, but I can imagine soon since they are targeting enterprises.

**Comment by phillipremaker** [comment]
AWESOME! Thanks!

**Comment by NiKiZe** [comment]
Any update on this? Could I suggest that you reopen this issue until IPv6 is resolved? Or is it some other issue that is still open covering this?

**Comment by jimaek** [comment]
What endpoint are you talking about? stackpath.bootstrapcdn.com still works over ipv6

**Comment by NiKiZe** [comment]
> What endpoint are you talking about? stackpath.bootstrapcdn.com still works over ipv6

I encountered maxcdn.bootstrapcdn.com in the wild where IPvFoo showed v4 while everything else was v6.
Can not reproduce now, so probably a bad cache for some reason. Sorry for the noise.
