### ISSUE TITLE
Please also host the ie10-viewport-bug-workaround.js

### ISSUE THREAD

**Issue by marceloverdijk** [MaxCDN/bootstrap-cdn#537]
See http://getbootstrap.com/getting-started/#support-ie10-width

And the actual file: http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js

**Comment by jmervine** [comment]
@jdorfman thoughts?

**Comment by Batmanian** [comment]
Seconded, thanks.

**Comment by jdorfman** [comment]
@jmervine lets do it, please minify it and put it in `public/js/`

**Comment by jdorfman** [comment]
@marceloverdijk @Batmanian sorry for the delay:

https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js

@jmervine want me to commit and push it?

**Comment by jmervine** [comment]
@jdorfman either way, I can take care of it tonight. Should we add mention of it on the site?

**Comment by jdorfman** [comment]
@jmervine awesome thanks. no mention needed.  Good idea, but lets just keep it simple, put it in the `js` folder.

**Comment by marceloverdijk** [comment]
Thx!!

**Comment by jdrda** [comment]
For those of us who wants to have clear production mix of Javascript and Stylesheet, like via Laravel Elixir, I made a new repo registered with Bower to have these files offline:
[https://github.com/jdrda/ie10-viewport-bug-workaround](https://github.com/jdrda/ie10-viewport-bug-workaround)

**Comment by alxpck** [comment]
Thank you! Could you include the link (https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js) in the Getting Started documentation for the CDN files? 

http://getbootstrap.com/getting-started/#download-cdn

**Comment by jdorfman** [comment]
@alxpck we have no control over that since it is a separate project. Also, it is such a niche issue I don't think it warrants shelf space. It is one Google/Bing/DDG search away.

**Comment by alxpck** [comment]
Ah! Sorry, I should have looked more closely at the project before posting. Thank you.

**Comment by jdorfman** [comment]
@alxpck no worries =)

**Comment by mrlife** [comment]
Does Bootstrap 4 need this, as well? Thanks for your help!
