### ISSUE TITLE
Access denied for font-awesome.min.css

### ISSUE THREAD

**Issue by sanjayankur31** [MaxCDN/bootstrap-cdn#544]
I'm getting this page instead of the fontawesome css:

http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/A.font-awesome.min.css.pagespeed.cf.HpcIsdYD5q.css

The URL in the source HTML is correct: 

//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

Not sure what's causing this, and it isn't reproducible all the time either. Any ideas?

**Comment by jdorfman** [comment]
Do you have a url where I can reproduce this?

**Comment by sanjayankur31** [comment]
Yeah. I just rechecked - http://ankursinha.in/blog/ using Firefox. Viewing the source gives this for the css: http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/A.font-awesome.min.css.pagespeed.cf.HpcIsdYD5q.css 

(Similar over my phone too at the moment)

Site's still syncing via FTP, some pages would return a 404 :)

**Comment by jimaek** [comment]
You are using Pagespeed on your server. You need to add bootstrapcdn to exceptions

**Comment by sanjayankur31** [comment]
Ah! That was indeed the issue. Adding this to .htaccess seems to have fixed it:

``` 
    ModPagespeedDisallow "*/font-awesome.min.css"
    ModPagespeedDisallow "*/bootstrap.min.css"
```

Closing! Cheers!

**Comment by jdorfman** [comment]
Thank you @jimaek and @sanjayankur31

**Comment by jmervine** [comment]
:+1:
