### ISSUE TITLE
Paper theme v3.0.2 CDN not working

### ISSUE THREAD

**Issue by diegojancic** [MaxCDN/bootstrap-cdn#554]
Trying to load

    http://netdna.bootstrapcdn.com/bootswatch/3.0.2/paper/bootstrap.min.css

I get an AccessDenied error.  I know this is similar to #337, but since it's for another version I decided to create a new issue.

BTW, I'm using Drupal's release version and it's pointing to this file. Thanks.

**Comment by jdorfman** [comment]
Hey @diegojancic looking into it now

**Comment by jdorfman** [comment]
Hey @diegojancic just checked and the `Paper` theme didn't arrive till `3.2.0` hence why it is sending a `400` response.  Please let the developer know and use this url:

`https://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/paper/bootstrap.min.css`

**Comment by diegojancic** [comment]
Ohh, then it's Drupal's theme bug.  Thank you!

**Comment by jdorfman** [comment]
@diegojancic np =)
