### ISSUE TITLE
Add support for SRI

### ISSUE THREAD

**Issue by jonathanKingston** [MaxCDN/bootstrap-cdn#555]
As a CDN provider it will soon become good practice to provide integrities.
See:
https://github.com/jsdelivr/jsdelivr/issues/6029
https://github.com/cdnjs/cdnjs/issues/4599

For all static assets that never change can integrities be added?

I'm here to help if anything is needed.

**Comment by jdorfman** [comment]
Hey @jonathanKingston,

[I agree](https://twitter.com/jdorfman/status/593816398750711808) SRI will be a great once the W3C spec is finished.  Correct me if I am wrong, but by adding it now:

* no user-agents (besides Firefox?) will recognize SRI hashes
* minor releases < `1.0.0` for `npm-sri-toolbox` will contain breaking changes

**Comment by ericlaw1979** [comment]
FWIW, Chrome implemented in June: https://code.google.com/p/chromium/issues/detail?id=355467

**Comment by jdorfman** [comment]
ah thank you @ericlaw1979

**Comment by jdorfman** [comment]
@jonathanKingston can you shoot me an email? jdorfman at maxcdn

Thanks!

**Comment by jdorfman** [comment]
@ericlaw1979 looks like `Chromium` has implemented `SRI` but has not hit `Chrome` just yet.  With that aside I still want to get this underway because I believe `SRI` is a really important incentive, especially for public CDN's. 

@jonathanKingston My question is the `crossorigin` attribute.  What does the `anonymous` value mean?  

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc=" crossorigin="anonymous">
```
Reason I ask is with CORS, as I'm sure you know, adding `*` represents all origins/domains can use the resource.  I hate assuming so before we continue, I want to make sure I don't advertise something that will break our users sites.

**Comment by jdorfman** [comment]
@freddyb can you help a SRI noob out? ^

**Comment by jonathanKingston** [comment]
@jdorfman sorry for the delayed response, just got home.

Anonymous means don't send credentials: https://www.npmjs.com/package/ember-cli-sri#crossorigin-attribute

**Comment by jonathanKingston** [comment]
Yup Chrome Canary has an implementation in for testing purposes.

There are some caveats however they **should** not be important here:

- Chrome will fail open if you don't specify the `crossorigin` attribute on CORS requests with no CORS headers (This is to protect private resources)
- The `fetch()` API changes are not implemented yet

The spec changes that have been mentioned so far:
- fail closed on all CORS requests. So integrity checking won't happen unless it is specified. Which means if no CORS headers are returned then it will always fail in the network rather than being integrity checked conditionally.
- There are some upcoming wording changed to explain the rationale and other parts too.

So yeah `npm-sri-toolbox` shouldn't be changing in shape here any longer, however I understand your hesitation there.

**Comment by jdorfman** [comment]
@jonathanKingston that clears everything up for me.  I will work with @jmervine on getting something implemented in the near future.

**Comment by jdorfman** [comment]
@jonathanKingston would it make sense to have a checkbox to toggle SRI until the spec is complete?  My fear is something [like this](https://ma.ttias.be/chrome-44-sending-https-header-by-mistake-breaking-web-applications-everywhere/) happens.

**Comment by jonathanKingston** [comment]
Before it is a 'last call' then certainly that might be a good idea. (I don't expect that time frame to be very long at all).

Long term it would be nice to not give people the choice in what they copy (educating developers that the feature exists is the core reason I am advocating it here :) ).

Please don't hesitate to pop me a mail if you have questions.

Thank you!

**Comment by jdorfman** [comment]
@jonathanKingston how about something like this:

![image](https://cloud.githubusercontent.com/assets/398230/8865219/d8f5cc0a-3160-11e5-8f5a-65aa21459903.png)

**Comment by jonathanKingston** [comment]
:+1: looks good to me

**Comment by jdorfman** [comment]
Alrighty then.  @jmervine and I will start working on this...Or you can make a PR and we love you long time ;)

**Comment by jonathanKingston** [comment]
Not today certainly, however I will look into it.

The hardest part of this task looks like moving out the file list here:
https://github.com/MaxCDN/bootstrap-cdn/blob/develop/config/_config.yml

To be generated by a script when you are adding a new version.

**Comment by jonathanKingston** [comment]
Also looks like the 'hellobar' code at the bottom of the page isn't there on localhost meaning I have to manually expand the code window as the toggle isn't working.

Nearly got a PR ready.

**Comment by jmervine** [comment]
Done https://github.com/MaxCDN/bootstrap-cdn/pull/564
