### ISSUE TITLE
Improve compression of static assets

### ISSUE THREAD

**Issue by ericlaw1979** [MaxCDN/bootstrap-cdn#556]
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css

Is served at 25,335 bytes using GZIP. If Zopfli (Google's gzip compressor) is used instead, the asset is 18408 bytes, 28% smaller! 

Essentially all static assets should be compressed with Zopfli for savings of 7% or more. 

http://textslashplain.com/2015/07/16/zopfli-all-the-things/ explains some background. It would be awesome if your CDN implemented this to save bandwidth costs and improve performance.

**Comment by jdorfman** [comment]
Thank you @ericlaw1979 we are looking into this. =)

**Comment by jmervine** [comment]
@ericlaw1979 (cc @jdorfman)

Currently we're compressing on the origin via the [compression module](https://www.npmjs.com/package/compression) implemented with the defaults [here](https://github.com/MaxCDN/bootstrap-cdn/blob/develop/app.js#L43).

This is a cool idea, and  I was able to build the [more popular Zopfli module](https://www.npmjs.com/package/node-zopfli) without issue on our provider, which is good. I'm going to need to do some research to figure out the best way to implement this within our current framework.

Cheers!
J

**Comment by jdorfman** [comment]
@jmervine would this work? https://www.npmjs.com/package/node-zopfli

Thanks for the kick in the ass @ericlaw1979 =)

**Comment by jmervine** [comment]
@jdorfman Let's talk about this offline, I don't think the additional compression (estimated @ 7% above) is worth the additional processing time (per the docs: "It is considerably slower than gzip (~100x) so you may want to use it only for static content and cached resources."). Given that a decent percent much of our traffic hit's www.bootstrapcdn.com directly (as opposed to maxcdn.bootstrapcdn.com), I would expect to this to have a fairly significant impact on performance, both to those end-users and our platform.

**Comment by ericlaw1979** [comment]
@jmervine: You absolutely wouldn't want to do this for non-static resources. The idea here is that you Zopfli the static assets you're serving (specifically, Bootstrap and other libraries) *once* and store the output to disk. You then return that pre-compressed content from disk instead of using slower / worse dynamic compression on the fly.

Popular servers (Apache, nginx, etc) have modules that support this; typically you just have file.js and file.js.gz and the server returns the latter if the client's Accept-Encoding headers are compatible.

**Comment by jmervine** [comment]
@ericlaw1979 I considered pre-compressing static assets. We host our origin in s3 currently. After a little research, it looks like S3 will support serving both compressed and non-compressed assets side by side, but I'll have to do some testing around. It have it on my todo list to automate our push to s3, once done, I'll see about adding a pre-compression step. I'm going to put this on hold for now, but I do like idea, if it can be done without too much overhead.

@jdorfman as always, you dictate priority. So if this become's a hot topic for you, let me know.

Cheers!

**Comment by jdorfman** [comment]
@ericlaw1979 just to confirm, you are saying if we turn off gzip on the CDN (nginx) and upload `file.js` and `file.js.gz` to S3 the Vary Accept-Encoding header will pick up the Zopfli compressed from S3?

**Comment by ericlaw1979** [comment]
@jdorfman The `http_gzip_static` module for nginx provides the functionality whereby pre-compressed assets are served to clients that can handle them. 

http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by jdorfman** [comment]
@ericlaw1979 awesome I will see if it is compatible with our build.

**Comment by jdorfman** [comment]
@ericlaw1979 Please explain the differences between `brotli` `gzip` & `zopfli`.

Reason I am asking is we decide to go forward with your proposal, will we have to scrap that and come up with a whole new build process for when `brotli` is the next best practice?

**Comment by ericlaw1979** [comment]
`Brotli` is a new Content-Encoding compression which is **not** compatible with `DEFLATE`; it offers better compression ratios than `DEFLATE` (which is the compression algorithm behind `Content-Encoding: gzip` and `Content-Encoding: deflate`). For instance, https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css is served at 16,130 bytes using `brotli`, 12% smaller than Zopfli.

Currently, no browser supports `brotli` but early next year both Chrome and Firefox should. These browsers, on HTTPS connections, will send `Accept-Encoding: gzip, deflate, brotli`. You can learn more about brotl here: http://textslashplain.com/2015/09/10/brotli/

In contrast, `zopfli` is simply a new engine for implementing the `DEFLATE` compression algorithm; it simply does a better job of compressing content than earlier engines like `zlib` or `mod_gzip`. Its output is fully compatible with any browser that today sends `Content-Encoding: gzip` or `Content-Encoding: deflate`.

**Comment by jdorfman** [comment]
@ericlaw1979 awesome answer.  I will have an answer soon.

**Comment by jdorfman** [comment]
@ericlaw1979 After talking with our engineering team Zopfli can be done.  I am going to keep this open until we can find a way to do this without hindering our current process.  I want to do this, I think it will help make the web faster, but the proposed solution is hacky.

**Comment by ericlaw1979** [comment]
Great to hear, thanks. FWIW, Google has released an nginx module for doing Brotli compression, so whatever approach you take will likely bear even more fruit when it can be used for Brotli as well. https://github.com/google/ngx_brotli. (I prefer Google's module because CloudFlare's new one only seems to offer on-the-fly compression)

**Comment by jdorfman** [comment]
@ericlaw1979 yes I saw that and I am talking to our engineering team to start testing it so when browsers start adopting it our customers (and BootstrapCDN) can take advantage.  I will update this thread with progress.

**Comment by amikoreh** [comment]
Is it possible to add http2 support? BootstrapCDN still using http/1.1.

I know [MaxCDN is now supporting http2](https://www.maxcdn.com/blog/http2-support/).

Much appreciated.

**Comment by jdorfman** [comment]
@amikoreh with SPDY I did numerous tests and found with BootstrapCDN, it was slower that `HTTP/1.1`. I do plan on testing with `H/2` but haven't had time to get around to it. I will try later this week on a test/QA CDN account.

**Comment by jdorfman** [comment]
@ericlaw1979 going to start rolling this out tomorrow: https://www.maxcdn.com/blog/gzip-compression-levels/

Brotli is on deck =)

**Comment by ericlaw1979** [comment]
Happy to see this, but I worry that the claim in the blog post (level 1 is easiest to decompress) is both unsupported and inaccurate. Can you elaborate on how you reached this conclusion?

Do your levels include a Zopfli level?

**Comment by jdorfman** [comment]
> I worry that the claim in the blog post (level 1 is easiest to decompress) is both unsupported and inaccurate. Can you elaborate on how you reached this conclusion?

Complete assumption. I can't really imagine anything other than level 1 being easier (or faster), but no tests (that I ran) to verify.

> Do your levels include a Zopfli level?

Unfortunately not at this time.

**Comment by XhmikosR** [comment]
So, guys any news about Brotli? There's already an nginx module available.

**Comment by jdorfman** [comment]
@XhmikosR I pushed before I left but there were other (customer) priorities.

**Comment by XhmikosR** [comment]
@jdorfman: thanks. If there's someone we could bug about this, let me know.

I believe adding brotli is a must nowadays with more than 50% of the users having a browser that supports brotli.

**Comment by jdorfman** [comment]
`@stackpath` on Twitter might be the best channel for this. I am going to run a poll on Twitter.

**Comment by jdorfman** [comment]
Since I no longer work for MaxCDN/StackPath I don't have insight into their roadmap. I also have little to no influence on features.

**Comment by eustas** [comment]
Is is possible to use `pre-compressed-assets` middleware + a little bit of build magic to enable serving of pre-compressed assets?

**Comment by jdorfman** [comment]
@eustas anything is possible but if it isn't in the MaxCDN/StackPath product we can't use it. At peak hours, we handle close to 26k requests/sec. Any solution has to scale to that and beyond (there are MaxCDN customers that put that number to shame).
