### ISSUE TITLE
Allow NPM-style semantic versioning in URLs

### ISSUE THREAD

**Issue by aendrew** [MaxCDN/bootstrap-cdn#570]
As per [here](https://twitter.com/aendrew/status/633947678402060288) — currently there are two ways of getting a library from MaxCDN: 

* Via specific version number: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
* Via "latest": https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css

Using the example of Twitter Bootstrap, recently I was building a template for a system that generates static HTML one-pagers. I'm consuming Bootstrap via MaxCDN, and it'd be nice for my output to update to the latest bugfix version of Bootstrap automatically while not updating to the latest minor/major versions. 

Is this:
a. Possible?
b. Not an absolutely terrible idea?

Thanks!

**Comment by jmervine** [comment]
@aendrew Thanks for opening this, this at least gives us a place to discuss.

@jdorfman 

I started thinking last night about this, it would be easy enough to automate (either through a pre-generation script or a route) linking `3 -> 3.<max>` and `3.n -> `3.n.<max>`. My concern here is implementing cache purges in a way that makes sense and pushing to the origin bucket properly.

Ideally, I'd like to support standard [`semver`](https://github.com/npm/node-semver) in the routing, through the node app and have that pass through to the CDN with a greatly reduced timeout (perhaps 5 days?). Depending on how well this this type of usage takes off, it could greatly increase MISS rates though.

The pro is, it would support things like `/bootstrap/^3.5/...`, `/bootstrap/^3.3.0/...`, etc...

Additionally, I could map standard base comparators where `gt == '>'`, `ge == '>='`, etc. Allowing for things like `/bootstrap/ge2.5.0/...`, `/bootstrap/gt2.5/...`, `/bootstrap/le3.5/...`, etc.

Of course, while this all could work in theory, I'd need to do some testing.

What are your thought?

J

**Comment by jimaek** [comment]
Technically OSSCDN already supports that

//oss.maxcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
//oss.maxcdn.com/bootstrap/3.3/css/bootstrap.min.css //latst 3.3.x
//oss.maxcdn.com/bootstrap/3/css/bootstrap.min.css //latest 3.x
//oss.maxcdn.com/bootstrap/latest/css/bootstrap.min.css //latest

**Comment by jmervine** [comment]
@jimaek What's your implementation on this? Symlinks?

**Comment by jimaek** [comment]
Its a dynamic script that calculates the version on the fly. Then it gets cached by the CDN as a static fille.

**Comment by jmervine** [comment]
Okay, that's basically what I was thinking.

**Comment by jdorfman** [comment]
Possibly.  @aendrew for now I would use osscdn.com for this.  Same network just a different hostname.

**Comment by aendrew** [comment]
@jdorfman Cool! Sounds like a plan, many thanks!
