### ISSUE TITLE
Glyphicons not loading in Bootswatch 3.3.5

### ISSUE THREAD

**Issue by isabelleflores** [MaxCDN/bootstrap-cdn#573]
For example, `GET file:////src/node_modules/bootswatch/fonts/glyphicons-halflings-regular.woff2 net::ERR_FILE_NOT_FOUND`

Dropping down to 3.3.4 fixes the issue.

**Comment by jmervine** [comment]
@isabelleflores Not 100% sure of the context here, as I have never used the bootswatch npm's, but I think you meant this gh:issue for the bootswatch project @ https://github.com/thomaspark/bootswatch.

Let me know so I can close this, or address as needed.

Cheers!

**Comment by isabelleflores** [comment]
I saw https://github.com/MaxCDN/bootstrap-cdn/issues/527 in this project so opened something similar. Seems more suited for the bootswatch project though, I'll close this :)

**Comment by jmervine** [comment]
@isabelleflores thanks!
