### ISSUE TITLE
SSL error on https://www.bootstrapcdn.com/

### ISSUE THREAD

**Issue by hubdotcom** [MaxCDN/bootstrap-cdn#574]
![3108b178-52fe-11e5-97ab-f8d34edea933](https://cloud.githubusercontent.com/assets/5274747/9689145/43008208-5334-11e5-98c2-2113e3cea93f.png)

**Comment by jdorfman** [comment]
Hey @hubdotcom 

Thanks for reporting, we are aware of it and will install the cert on heroku soon. cc: @jmervine

**Comment by jdorfman** [comment]
@jmervine getting the key from ops to upload to heroku

**Comment by jdorfman** [comment]
Provisioning. Can take anywhere from 30min - 2 hours

**Comment by jdorfman** [comment]
@jmervine It has been 4 hours and SSL still hasn't provisioned on Heroku...

**Comment by jdorfman** [comment]
Fin: https://www.bootstrapcdn.com/

**Comment by dovidweisz** [comment]
https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css

broken for me :(

**Comment by jdorfman** [comment]
@dovidweisz we are working on it

FWIW this is what happened: http://www.theregister.co.uk/2016/10/13/globalsigned_off/

**Comment by jdorfman** [comment]
@dovidweisz please check again

**Comment by dovidweisz** [comment]
@jdorfman 
Works from my smartphone...
I was tethering my laptop off this device earlier. I think it's safe to assume that they "dns the same way" and the issue is resolved.

**Comment by email2hirenshah** [comment]
Getting SSL error when browse https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js  from latest Firefox browser on Windows 10 machine.

This is happening when I install latest Firefox on a machine where it didn’t existed before.

**Comment by petarpetrovic** [comment]
Hey @email2hirenshah, sorry to hear that. Could you possibly give me some additional info?

1. What's the exact error message you get when you try to load that URL?
2. Do you get the same error message when you try to load some other URL under that hostname?
3. Could you perform a HEAD request with `curl` or a similar tool and paste the output here? (Like this: `curl -I https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js`)

Please keep me posted.
