### ISSUE TITLE
fontawesome svg blank?

### ISSUE THREAD

**Issue by diomed** [MaxCDN/bootstrap-cdn#590]
I'm a bit confused as to why is this blank:
https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular

**Comment by jdorfman** [comment]
Hey @diomed it is straight from the fine folks at font awesome.  I see the mime type and size is correct:

```
$ icurl https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.svg
HTTP/1.1 200 OK
Date: Tue, 10 Nov 2015 22:27:34 GMT
Content-Type: image/svg+xml
Content-Length: 355981
```

As well as the `MD5` hash:

```
$ curl -s https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.svg |md5
76a4f23c6be74fd309e0d0fd2c27a5de

$ curl -s https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/fonts/fontawesome-webfont.svg |md5
76a4f23c6be74fd309e0d0fd2c27a5de
```

**Comment by diomed** [comment]
shouldn't this have some content, like here:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/fonts/fontawesome-webfont.svg

**Comment by jimaek** [comment]
That domain sends a `text/plain` content-header, thats why it displays the source as clear text.

**Comment by jdorfman** [comment]
@diomed good question but as @jimaek said, different content-header.
