### ISSUE TITLE
Bootlint 0.14.1 and 0.13.0 have been released

### ISSUE THREAD

**Issue by cvrebert** [MaxCDN/bootstrap-cdn#591]
See https://github.com/twbs/bootlint/releases/tag/v0.14.1
Unless you're completeness junkies, you might as well just skip over 0.13.0.
And 0.14.0 was buggy; definitely skip it.

**Comment by jmervine** [comment]
thanks for the heads up, on it

**Comment by jmervine** [comment]
done
