### ISSUE TITLE
Glyphicons broken in v3.3.6 on BootstrapCDN

### ISSUE THREAD

**Issue by goodsoft** [MaxCDN/bootstrap-cdn#620]
When including CSS from https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/sandstone/bootstrap.min.css everything works fine and all icons are displayed correctly.
Changing URL to https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/sandstone/bootstrap.min.css shows generic "missing character" glyphs.

I noticed that woff2 file in 3.3.6 became two times larger than before.

P.S. Reposting issue from thomaspark/bootswatch#538 as per maintainer's request.

**Comment by jmervine** [comment]
@goodsoft (cc @jdorfman @thomaspark)

I've confirmed that the files on the CDN match the files downloaded from bootswatch (size change and all). Additionally I've ensure that the pathing is correct in (one of) the bootstrap.css files. I did make a small perms change on the origin host, but that really shouldn't be the difference there.

Lastly, I'm not able to reproduce this issue on Chrome (Version 47.0.2526.106 (64-bit)
) or Firefox (42.0) -- both on Mac 10.10.5 -- when hitting www.bootstrapcdn.com which is using bootswatch 3.3.6.

**Comment by jmervine** [comment]
Actually, when downloading the file manually, via curl as opposed to my script, I noticed that the `md5sum`s were different. So there might be an issue with my download script. I'll dig in.

**Comment by jdorfman** [comment]
@goodsoft looking into this now.

**Comment by goodsoft** [comment]
Yes, md5s really are different:

`448c34a56d699c29117adc64c43affeb http://bootswatch.com/fonts/glyphicons-halflings-regular.woff2`
`448c34a56d699c29117adc64c43affeb https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/fonts/glyphicons-halflings-regular.woff2`
`5e8b122233593cfb2b7ad16d11d85937 https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/fonts/glyphicons-halflings-regular.woff2`

**Comment by jdorfman** [comment]
as @goodsoft mentioned the `md5sums` are different.

`glyphicons-halflings-regular.eot` on the CDN was wrong: 
`9f0aa0d814d27edbb5f874757658dcc7`

The correct hash is: 
`f4769f9bdb7466be65088239c12046d1`

The CDN has been updated, cache purged. We apologize for the screw up and we are going to fix `scripts/bootswatch.js` immediately.

Please let us know if you need any further help.
