### ISSUE TITLE
sourceMappingURL files 403 response

### ISSUE THREAD

**Issue by thebeebs** [MaxCDN/bootstrap-cdn#629]
I was just investigating this issue on stackoverflow http://stackoverflow.com/questions/35142485/why-is-bootstrap-trying-to-load-less-files-in-ie-edge/35151109#35151109 and it became apparent that the less files declared in the bootstrap.min.css.map file are 403'ing

This is currently breaking SourceMap debugging in browser tools such as Edge and Chrome F12 tools.

**Comment by jmervine** [comment]
@thebeebs Thanks for bringing this to our attention. It might take a little bit, but we'll resolve.

**Comment by jdorfman** [comment]
@thebeebs as @jmervine said thanks for reporting this.  I will see if I can reach anyone on the Edge team.

**Comment by thebeebs** [comment]
Another option would be to remove the sourcemapurl comment from the css file or in the map file provide full urls to the files on GitHub (they don't have to be hosted on your cdn)

**Comment by jmervine** [comment]
@thebeebs I thought about that. I don't know that it's a valid option long term as our general policy is not to modify files that come from our sources, aside from perhaps minifying where necessary. That said, if @jdorfman is cool with it, we could consider doing it as a stop gap.

**Comment by jdorfman** [comment]
@jmervine correct I don't want to change that policy, I rather just start delivering the `.less` files.  So we just need to adjust the current workflow.

**Comment by jmervine** [comment]
I'll work on something this weekend to batch update the perms for `*.less` files on the origin.

**Comment by jdorfman** [comment]
:+1:

**Comment by nebeleh** [comment]
any updates on the issue? I do have the same problem.

**Comment by jmervine** [comment]
@nebeleh No sorry, I didn't get to this. I will though. Thanks for the ping as a reminder. :D

**Comment by jmervine** [comment]
@jdorfman @nebeleh This is actually a bit more work to resolve. The issue is, we haven't in the past uploaded `less` files to the s3 bucket, and there's quite a few spread through out. I'll get to it, but probably not this week. I'll shoot for the weekend. 

Cheers!
J

**Comment by jmervine** [comment]
Okay, I've uploaded and verified perms on all `.map`, `.less` and `.scss` files. Please open an new issue, or reopen this one if you come across anything else that's missing / incorrect.

**Comment by jdorfman** [comment]
@thebeebs @nebeleh please confirm. Thanks!

**Comment by nebeleh** [comment]
Thank you for checking on this. Although I still do have some issues, especially when using Edge. I'm using bower to load up bootstrap from https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min, but I receive this error in console: `HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://.../bower_components/bootstrap/dist/css/less/normalize.less` plus a similar message for many other `.less` files inside bootstrap. It may not have any actual effect on the final code, yet it would be nice if I can resolve them. Should I use a different version for the CDN?

**Comment by patrickhlauke** [comment]
> ![capture](https://cloud.githubusercontent.com/assets/895831/13196528/03b66a4a-d7c8-11e5-8a78-136477775dfb.PNG)

Just confirming that it's still 403-ing all over the place. Is there something that needs to be enabled at Bootstrap's end? See https://github.com/twbs/bootstrap/issues/19063#issuecomment-178806421

**Comment by jdorfman** [comment]
@patrickhlauke thanks. @jmervine and I will keep digging in.

**Comment by jdorfman** [comment]
@patrickhlauke @cvrebert would it be possible to remove `/*# sourceMappingURL=bootstrap-theme.min.css.map */` from the `.min` files on build?

Or at least help me understand why it is necessary?

We prefer to serve the exact file from GitHub so everyone can be assured that we are not injecting anything, hence why we leave it in.

Thanks!

**Comment by cvrebert** [comment]
Assuming we can rejigger the sourcemap to not reference external Less filepaths (which I believe is possible; see https://github.com/twbs/bootstrap/issues/19063), it shouldn't be necessary to disable/remove sourcemaps from the CSS (nor to host any Less files).

**Comment by jdorfman** [comment]
@cvrebert that would be ideal.  Let us know if we can be of help in anyway.

**Comment by jmervine** [comment]
@jdorfman I was able to reproduce on iOS Chrome for the bottom link, but
not top. I can fix that within the hour if you don't get to it first.

J

**Comment by jmervine** [comment]
@wingnut808 You're getting 403 on http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/less/normalize.less, because we don't provide that file and 403 is the default response for a missing file in AWS S3. As for http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css, I verified the perms on it and they look right... mind running a quick curl HEAD request and dumping me the output... for example...

```
jmervine@laptop:~$ curl -s -I http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
HTTP/1.1 200 OK
Date: Tue, 31 May 2016 14:46:13 GMT
Content-Type: text/css
Content-Length: 121260
Connection: keep-alive
Last-Modified: Tue, 24 Nov 2015 19:49:46 GMT
ETag: "2f624089c65f12185e79925bc5a7fc42"
Server: NetDNA-cache/2.2
Expires: Fri, 26 May 2017 14:46:13 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: You should work for us! Email: jdorfman+theheader@maxcdn.com or @MaxCDNDeveloper on Twitter
X-Cache: HIT
Accept-Ranges: bytes

```

**Comment by cvrebert** [comment]
Sorry folks. I'll try to take another look at https://github.com/twbs/bootstrap/issues/19063 soon.

**Comment by jmervine** [comment]
@cvrebert No worries, thanks for jogging my memory on it. I knew we had a solution, but I couldn't remember what it was.

**Comment by jdorfman** [comment]
@jmervine it is strictly a Edge issue, which isn't really their fault. Chrome ignores the 4xx errors. Hopefully twbs/bootstrap#19063 fixes it for future releases.

**Comment by jdorfman** [comment]
I am reopening this until twbs/bootstrap#19063 is resolved.

**Comment by bhavik3184** [comment]
+1 for me its failing on Edge!! :(

**Comment by timc4** [comment]
I will be out of the office from Friday 06/24/2016 until Monday 06/27/2016  

If you need assistance during that time frame, please email surf@c4.net and you will be directed to the person best suited to help you.  

Thanks,  

Tim

**Comment by ryuker16** [comment]
happening to me as well on all browsers

**Comment by jdorfman** [comment]
@bhavik3184 @ryuker16 copy that. I will do **my best** to get this resolved.

**Comment by jdorfman** [comment]
@thebeebs @nebeleh @patrickhlauke @wingnut808 @ryuker16 @bhavik3184 please test this: https://maxcdn.bootstrapcdn.com/debug/fix-19063-v3/css/bootstrap.min.css and report whether it works or not. Thanks.

**Comment by jdorfman** [comment]
Looks like this will be resolved soon. @XhmikosR confirmed that @cvrebert's fix worked. 

**No more `4xx` errors:**
![image](https://cloud.githubusercontent.com/assets/398230/16739657/15fe3f0a-4750-11e6-8db9-79e1b7eaaeba.png)

**Comment by cvrebert** [comment]
@jdorfman So, we done here, now that 3.3.7 is out with the fix?

**Comment by jdorfman** [comment]
@cvrebert yes. Thanks to everyone involved. I'm having issues updating the BootstrapCDN homepage so here you go:

```html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

**Comment by gitwith** [comment]
I still get the errors with debugger in ie11 when specifying: https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css

It complains of missing links from map file: 
"Could not locate https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/less/print.less in source map https://msxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css.map"

**Comment by jdorfman** [comment]
@gitwith we don't add `bootstrap.min.css.map` to `/latest/`. Please choose `/3.3.7/`
