### ISSUE TITLE
Full html5 boilerplate sample?

### ISSUE THREAD

**Issue by fuzzy76** [MaxCDN/bootstrap-cdn#631]
I was looking for a quick way to make a one-page script using bootstrap, and decided this was a good way to do that. What would make it even easier would be if there was a HTML5 boilerplate document I could copy-paste to get it all. :)

**Comment by jmervine** [comment]
I typically start here: http://getbootstrap.com/getting-started/. I'm thinking that's a bit out of our domain, although I'll admin, I've been consider creating a github repo with some starting templates I use.

@jdorfman thoughts?

**Comment by jdorfman** [comment]
@fuzzy76, @jmervine is right, getbootstrap.com will always have the best and up to date one-page template.  With that said, BootstrapCDN does have some great integrations that can help speed up development: http://www.bootstrapcdn.com/integrations/
