### ISSUE TITLE
CDN v3.3.6 cross-origin request blocked

### ISSUE THREAD

**Issue by BernardA** [MaxCDN/bootstrap-cdn#637]
Hello

Getting above error during the last few days. Did work well before that.

This is the code, just in case:

`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap..js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
`

If I, instead, place  the CDN code for version 3.3.5 it works perfectly fine. 

See enclosure.

Regards
Bernard
![screen shot 2016-02-19 at 11 57 22](https://cloud.githubusercontent.com/assets/9449665/13188616/585e5914-d74a-11e5-9ce6-a1f28be4fd73.png)

**Comment by jmervine** [comment]
Thanks for reporting. I'll take a look.

**Comment by jmervine** [comment]
I did notice that you have two periods in the path, is that a reporting typo, or is that what you have in the actual code?

```
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap..js
```

**Comment by jmervine** [comment]
Additionally, I noticed that you have "sha384", but we provide "256" and "512" on the CDN, mind trying: 

```
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
```

**Comment by BernardA** [comment]
Hello

Thank you for your prompt reply.

The 2 periods were in the actual code, which *I promise you I copied from
your download page a few months ago* and it was actually working till
recently.

But then, of course, it stopped working.

I did correct the code, ie, removed the additional period at it is working
now.

Thanks again.

Bernard

**Comment by jmervine** [comment]
Awesome! Let us know if you have any more issues. :)
