### ISSUE TITLE
Standardize on sha384 SRI

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#638]
@jdorfman `sha384` seems to be the accepted default for SRI (see: https://w3c.github.io/webappsec-subresource-integrity/), I want to replace our current `sha256` & `sha512` with `sha384`.

Thoughts?

**Comment by jdorfman** [comment]
@jmervine I don't see that being an issue.  @jonathanKingston your thoughts please.

**Comment by jonathanKingston** [comment]
@jdorfman it's not an issue at all really, the standard permits all 3 to be used and mainly preferring for `sha384` I suspect as it's shorter but less collisions than `sha256`. There is likely to be so few malicious hashes at this stage that it's unlikely to be too much of an issue for security.
Long term the algo may matter more when browsers start considering using it for persistent caches for all webpages... that's a long way off though.

**Comment by jdorfman** [comment]
@jonathanKingston thank you for your insight. =)

**Comment by jdorfman** [comment]
@jmervine need to fix the Quick Start sha's, they still show `256` & `512`

![image](https://cloud.githubusercontent.com/assets/398230/13273193/87ed6c24-da56-11e5-94be-1a353278c71e.png)

**Comment by jmervine** [comment]
@jdorfman 

Browser caching, if you shift reload, it should look right... 
![sha384ss](https://cloud.githubusercontent.com/assets/837893/13296099/a7f8fcf6-dae0-11e5-9459-398261425cae.png)

At least, that's what I'm seeing (and the config has the correct sha384 value). Mind verifying for me?

**Comment by jdorfman** [comment]
@jmervine my bad.  Works.
