### ISSUE TITLE
Add referrer meta tag to website

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#641]
Since moving to SSL only on the site, I would like to add this meta tag.  Not high priority.

`<meta name="referrer" content="origin">`

**Comment by XhmikosR** [comment]
I'd say `rel="canonical"` should be used.

https://yoast.com/rel-canonical/

**Comment by jmervine** [comment]
@jdorfman Seems legit, I'll let you make the call.

**Comment by jmervine** [comment]
@jdorfman Any opinions on this?

**Comment by jdorfman** [comment]
@XhmikosR create a PR =)

**Comment by XhmikosR** [comment]
Not sure how to do it with Jade. I still have a long to do list for this
repo....

**Comment by jmervine** [comment]
Here's an example of a meta tag: https://gist.github.com/xtian/888338#file-html5boilerplate-jade-L5.

That said, I don't mind doing it if you don't have the bandwidth.

**Comment by XhmikosR** [comment]
The canonical tag needs to get the current page's URL. Since you are more
familiar with Jade than me it should be easier for you.

**Comment by jmervine** [comment]
@jdorfman @XhmikosR Is the suggestion `canonical` over `referrer` or both?

**Comment by jmervine** [comment]
Never mind, `referrer` is already there.

**Comment by XhmikosR** [comment]
My personal choice is definitely only canonical.
