### ISSUE TITLE
bootstrap.css and bootstrap.min.css for version 3.3.6 

### ISSUE THREAD

**Issue by killerog** [MaxCDN/bootstrap-cdn#656]
Hello,

I've recently been modifying a joomla template that included a link to bootstrap on your cdn. There I encountered a bug which I had some troubles with to reproduce.
Finally I noticed that some styling was applied on the frontpage, but not on the other pages. Then I found out that the frontapge links to https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css and the other pages to https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
In the non-minified version this css selector seems to be present: 
`@media (min-width: 768px) {
  .navbar > .container .navbar-brand,
  .navbar > .container-fluid .navbar-brand {
    margin-left: -15px;
  }
}`
but not in the minified version.

I don't know if we're even supposed to link to the non-minified version, but maybe you can look into this.

**Comment by jdorfman** [comment]
@killerog you are correct.  Digging what happened and what the next steps are.

**Comment by jdorfman** [comment]
First, my apologies for the first comment I left, I was testing the wrong Bootstrap version.

Second all we (the CDN) do is upload the files downloaded straight from [twbs/bootstrap releases](https://github.com/twbs/bootstrap/releases/tag/v3.3.6) and serve them on our network.

Here are SHA-2 (384 variant) hashes I generated to confirm:

|source|file|hash|
|---|---|---|
|[GitHub](https://github.com/twbs/bootstrap/releases/download/v3.3.6/bootstrap-3.3.6-dist.zip)|`bootstrap.min.css`|`1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7`|
|[BootstrapCDN](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css)|`bootstrap.min.css`|`1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7`|

**Hash generation method:**
`openssl dgst -sha384 -binary | openssl base64`

Can you download the file in question to your hard drive and upload it to gist.github.com so I can analyize further? Also go to http://debug.netdna-cdn.com/ and paste the output?

Thanks!

**Comment by killerog** [comment]
@jdorfman Thanks for checking it out, but I don't think anymore that it's a CDN issue. If I manually download the bootstrap release files they appear the same. The style is available in both versions, but just doesn't gets applied if you use the minified version.
I'll file my issue with bootstrap instead, sorry for the trouble.
