### ISSUE TITLE
Font awesome "latest" still using 4.6.2

### ISSUE THREAD

**Issue by ThomWilhelm** [MaxCDN/bootstrap-cdn#666]
When will the latest link for the font awesome library:

http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css

Reference the latest 4.6.3 release?

http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
http://fontawesome.io/

**Comment by jdorfman** [comment]
Weird looking into it.

**Comment by jdorfman** [comment]
@ThomWilhelm fixed, hashes now match:

```
$ sri384 http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1
```
```
$ sri384 http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css
sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1
```

My apologies. @jmervine lets add a unit test for this case.

**Comment by ThomWilhelm** [comment]
Cheers @jdorfman appreciate the quick fix!

**Comment by jmervine** [comment]
@jdorfman We check for the existence of sri [here](https://github.com/MaxCDN/bootstrap-cdn/blob/develop/tests/fontawesome_test.js#L25-L28) and for the accuracy of sri [here](https://github.com/MaxCDN/bootstrap-cdn/blob/develop/tests/fontawesome_test.js#L58-L64). Not sure why these didn't fail. I'll dig in. Created #667 as a follow up.
