### ISSUE TITLE
MS Edge: "Could not locate..."

### ISSUE THREAD

**Issue by AlchemyUnited** [MaxCDN/bootstrap-cdn#671]
On Chrome (PC), Firefox (PC) and "render in IE" (via Edge PC) all seems fine. The page looks as expected and I'm not seeing any errors in the console. 

However, in Edge I'm getting: 

"Could not locate https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/less/normalize.less specified in source map https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css.map."

In Edge Console I'm getting a whole load of these

403 -  FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(XHR)GET - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/less/normalize.less

No errors in the Edge Console, just a long list of 403s. 

Finally. What's odd - and yes I realize this kinda points the problem back at me - is I have another site / page based on the same HTML template that renders fine in Edge. Maybe that's from (Edge's?) cache? What happened was, I made some updates to the newer site, decided to check it in Edge and BOOM! 403s.

**Comment by jdorfman** [comment]
Thanks for reporting @AlchemyUnited. This is a known issue that the Bootstrap team is aware of. I'm going to keep it open for now and see if we can resolve this for future versions of Bootstrap.

**Comment by AlchemyUnited** [comment]
Okay. Thx.

I went back and looked at the site/page I thought was working and that's getting the 403s as well. The difference is that page still renders okay. 

Do you know if this is also an issue with local / non-CDN Bootstrap? 

Else, since they're pretty simple pages I'll just strip out only the BS3 CSS I need and have my own .css. 

Thoughts? Suggestions?

**Comment by jdorfman** [comment]
@AlchemyUnited It's not really an issue. It only appears when you open up dev tools. #629 has more info . 
Also forgot that the Bootstrap team is digging into this: https://github.com/MaxCDN/bootstrap-cdn/issues/629#issuecomment-222721093

I am going to close this issue and reopen the other. Thanks for reporting.

**Comment by AlchemyUnited** [comment]
@jdorfman  - thx again. i'll hold off a bit before i take evasive action.

**Comment by ashika789** [comment]
Have there been any updates on this? Having the same issue!

**Comment by jdorfman** [comment]
@ashika789 yes the Bootstrap team has fixed it and will be released soon. The version number will be `3.3.7`

see #629 for more info.
