### ISSUE TITLE
Split _config.yml into separate files

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#696]

**Comment by jmervine** [comment]
I'm on the fence on this. I kind of like having everything in a single location, it's suppose to take the place of a database. That said, I see why, it's gotten pretty unwieldy. @jdorfman thoughts?

**Comment by jmervine** [comment]
@XhmikosR 

Thought about this a bit more, here's what I'm thinking.

We can abstract each of the types in to their own file... (e.g. `config/_bootstrap.yml`, `config/_bootswatch.yml`, etc.). Additionally, I'd like to move the rest of the configuration out of a file all together and use more of the 12factor pattern of pulling configuration from the environment, which lines up with Heroku deployments, well. 

My concern in doing this is that you seem to have had some issues with setting environment variables.

I think https://www.npmjs.com/package/dotenv would be a possible solution for this. It's a pattern (including the `.env` file) I use heavily at work and in other (mostly Ruby && Golang) project, and it seems to work pretty well.

Thoughts?

**Comment by XhmikosR** [comment]
@jmervine: I haven't used dotenv, but if it works on Windows, which I don't see any reason not to, feel free to make a quick patch and see if AppVeyor works.

**Comment by XhmikosR** [comment]
Closing this since it's not so much of an improvement. We can revisit later.
