### ISSUE TITLE
Remove Makefile completely

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#698]
@jmervine: do you still use Makefile in the deployment process?

**Comment by XhmikosR** [comment]
@jmervine: do you still use Makefile in the deployment process?

**Comment by jmervine** [comment]
Yeah, 100%. That said, I don't need it. I added it b/c I use `make` in just about everything I do, mapping whatever task manager for whatever language I'm in to it. This allows for muscle memory on `make test`, `make run`, `make start`, etc. I can totally live without it if need be. I'm easy. =D

**Comment by XhmikosR** [comment]
It's not a big deal, I'm just trying to keep things simple :)

Let's wait a little bit for that because the Windows 10 anniversary update will have shell scripts native support.

**Comment by jmervine** [comment]
Sweet!

**Comment by jmervine** [comment]
Perhaps we should look at removing `make.js` and the `Makefile` and just make everything work using `npm run <action>`?

**Comment by XhmikosR** [comment]
We'd still need to run some scripts for this to work. Unless we end up
simplifying everything.

The current solution doesn't seem so bad to me. And if Windows users can
run shell scripts we could even go with that later.

**Comment by jmervine** [comment]
👍 on pure `bash`, when it's available. It's been forever, but I use to use cygwin for bash stuff back in the day.

**Comment by XhmikosR** [comment]
Yeah, I'm using MSYS but it's still not native.

Let's give it some time, it shouldn't be too long.

**Comment by jmervine** [comment]
Gotten out of the habit of using it anyway. Removed directly on develop here: https://github.com/MaxCDN/bootstrap-cdn/commit/5289cb1b63c6bcae5931f4e6d71531c19153d096.
