### ISSUE TITLE
IE < 9 compatibility for bootlint.min.js files

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#703]
We should specify the needed flags for uglifyjs since they changed the behavior recently.

https://github.com/MaxCDN/bootstrap-cdn/blob/develop/scripts/lint.sh

**Comment by XhmikosR** [comment]
So, do we support IE < 9 for bootlint.min.js?

/CC @jdorfman @jmervine

**Comment by jmervine** [comment]
@XhmikosR One of the (many) reasons I'm happy you're joining us on this is the neither @jdorfman or I have a tendency to think about Windows. To be honest, I haven't even used Windows -- aside from a quick test in a VM -- in close to 10 years. I think for that reason, we should defer to your judgement on this.

@jdorfman thoughts?

**Comment by XhmikosR** [comment]
The behavior was changed recently in uglify-js 2.7.0, which we get due to `^` in the dependency.

Can you check the stats how many users of bootlint have IE < 9? IE 8 is ancient and personally I ignore anything < 9, but this is a CDN we're talking about.

**Comment by XhmikosR** [comment]
/CC @jdorfman: I need the stats for bootstrap.min.js.

**Comment by jdorfman** [comment]
Overall `bootlint` isn't requested that much:

![image](https://cloud.githubusercontent.com/assets/398230/17423341/eba9bb08-5a6e-11e6-8535-edd0fd8b1d9a.png)

`/latest`

```
{
    "bytes": 2635524,
    "cache_hits": 96,
    "cache_misses": 3,
    "date": "2016-08-05T00:00:00.000Z",
    "hits": 99,
    "hostname": "maxcdn.bootstrapcdn.com",
    "http_requests": 4,
    "https_requests": 95,
    "statuscodes": [
        {
            "definition": "OK",
            "hit": 21,
            "status_code": "200"
        },
        {
            "definition": "Not Modified",
            "hit": 78,
            "status_code": "304"
        }
    ],
    "uri": "/bootlint/latest/bootlint.min.js",
    "url": "http://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js"
}
```
Our CP Raw Log viewer is limited with long tail URI's which means we would have to turn on Raw Log to S3 and parse through gigabytes of logs to get this answer. I don't mind doing it, it is just a matter of is it worth it? Let me know.

**Comment by XhmikosR** [comment]
Thanks for that. So it seems we shouldn't care about IE8 at this point.
