### ISSUE TITLE
Revisit cache control header

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#708]
For HTML we shouldn't have `2592000` s = 30 days. Maybe `3600` (1 hour) tops.

Now, for the static assets, CSS, images, JS, we **should** use a long time. But in order to prevent issues, we should add cache busting.

**Comment by jmervine** [comment]
Cache busting has been added: https://github.com/MaxCDN/bootstrap-cdn/pull/718

For html, it shouldn't be too difficult to wrap [these lines](https://github.com/MaxCDN/bootstrap-cdn/blob/develop/app.js#L56-L59) in a check, something like `if (req.path =~ /\.html$/ || !(req.path =~ /.*\.[a-z]{2,3}$/)) /* do_short_cache */` (<<untested)

**Comment by XhmikosR** [comment]
Or we could have a separate block in app.js?

**Comment by jmervine** [comment]
Yeah, or this actually should do the trict: https://github.com/expressjs/serve-static#maxage

**Comment by XhmikosR** [comment]
Yeah. We'll tackle all cache related stuff + ETags in one PR.

Just wait until we get the bootlint PR in so that tests pass again.
