### ISSUE TITLE
SSL for dev.bootstrapcdn.com

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#730]
Look in to possibly using heroku's free ssl addon?

**Comment by jmervine** [comment]
Look in to possibly using heroku's free ssl addon?

**Comment by jmervine** [comment]
Working on this now.

**Comment by jmervine** [comment]
This is pending a CNAME change by @jdorfman. My understanding is it'll be done in a week or so.

**Comment by XhmikosR** [comment]
Any news about this?

**Comment by XhmikosR** [comment]
Also, are there any other subdomains? If so, we should have SSL for all of them

**Comment by jmervine** [comment]
Dev is the only one without ssl. I wanted to try something that didn't require an dns change but just haven't had time. I'll get to it, it's dev so it's pretty low priority.

**Comment by jmervine** [comment]
This is done.

**Comment by XhmikosR** [comment]
@jmervine: is it possible to redirect http to https for the "dev" subdomain?
