### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#731]
Would be nice if we served with HTTP/2.

**Comment by jdorfman** [comment]
Back in the day, when I tested with SPDY on, I found single files like bootstrap.min.js actually hurt PLT rather than improve. I wish I saved the test results. With that said let's do some tests and see if my measuring was off. It could make a great blog post as well.

**Comment by jdorfman** [comment]
@jmervine when will Heroku have H/2?

**Comment by jmervine** [comment]
Unfortunately, I cannot comment on our roadmap. HTTP/2 is certainly something Heroku is interested in supporting in the future.

**Comment by XhmikosR** [comment]
Any updates on this? The CDN files are already using HTTP/2; only the website which is on Heroku doesn't use HTTP/2.

**Comment by jdorfman** [comment]
Still not supported: https://devcenter.heroku.com/articles/http-routing#not-supported

When it is supported, it will be on the front page of HN and we will enable it. For now, closing

**Comment by jdorfman** [comment]
Reopening this issue after receiving an email from a user. Going forward we will only be talking about H/2 for `cdn` (not `www`).

**Comment by XhmikosR** [comment]
The CDN files are already being served with http/2.

**Comment by jdorfman** [comment]
I thought they were but they aren't.

![image](https://user-images.githubusercontent.com/398230/33456301-da9b4e80-d5d3-11e7-8966-347da378115a.png)

Also checked with https://h2.nix-admin.com/#

**Comment by XhmikosR** [comment]
True, I also thought they were.

**Comment by jdorfman** [comment]
Monday we will enable it and watch the logs.

**Comment by petarpetrovic** [comment]
CDN assets are definitely not being served over HTTP/2 right now:

`Petars-MacBook-Pro:~ ppetrovic$ curl -I https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css --http2
HTTP/1.1 200 OK
Date: Thu, 30 Nov 2017 21:46:33 GMT
Content-Type: text/css
Content-Length: 121200
Connection: keep-alive
Last-Modified: Mon, 25 Jul 2016 16:08:01 GMT
ETag: "ec3bb52a00e176a7181d454dffaea219"
Server: NetDNA-cache/2.2
Expires: Sun, 25 Nov 2018 21:46:33 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: Say hello back! @getBootstrapCDN on Twitter
X-Cache: HIT
Accept-Ranges: bytes`

That will change on Monday 😎

**Comment by XhmikosR** [comment]
Maybe they were in the past? Because I'd swear they were...

**Comment by petarpetrovic** [comment]
It's possible HTTP/2 never got reactivated during the migration from the legacy MaxCDN infrastructure to StackPath. Unfortunately, I don't have sufficient information to confirm that, it's just my educated guess. Either way, it's getting reactivated soon.

**Comment by XhmikosR** [comment]
Yup, I'm right.

See https://gtmetrix.com/compare/CPIKVUkX/HiaFl5nH#waterfall

**Comment by jdorfman** [comment]
Checklist:

- [ ] Enable (@petarpetrovic )
- [ ] Tail logs (@petarpetrovic)
- [ ] Monitor Twitter (@jdorfman)
- [ ] 🍾

**Comment by jdorfman** [comment]
I always monitor Twitter so this case is closed.

**Comment by OlympicLarry** [comment]
Any reason why I am seeing http/1.1 now?
