### ISSUE TITLE
Page description should be unique and longer

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#738]

**Comment by jdorfman** [comment]
@XhmikosR 

`<meta name="description" content="The recommended CDN for Bootstrap, Font Awesome and Bootswatch.">`

**Comment by XhmikosR** [comment]
How is that unique per page?

**Comment by jdorfman** [comment]
ah, good point. I'll make a PR for this after I clean up the other issues.

**Comment by jdorfman** [comment]
@XhmikosR can you help with getting the `desc` values in the `pug` templates?

**Comment by XhmikosR** [comment]
Without having tried it. try passomg the descriptions similarly to the title here https://github.com/MaxCDN/bootstrap-cdn/blob/develop/routes/index.js#L45-L129

**Comment by jdorfman** [comment]
yikes, on it

**Comment by jdorfman** [comment]
@XhmikosR [passed](https://travis-ci.org/MaxCDN/bootstrap-cdn/builds/307197337)

Can you help with the template?
