### ISSUE TITLE
Cache busting edge case

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#740]
So, say one runs the local server with `node make run`. Then changes main.js or style.css; the SRI hash will change but the cache buster value will be the same until the server process is restarted.

@jmervine: Is there any way to work around this?

**Comment by jmervine** [comment]
Typical handling for stuff like this would be to disable cache busting in development.

**Comment by XhmikosR** [comment]
The problem is somewhere else and it's not cache related. The SRI doesn't match without restarting the server process...

**Comment by jmervine** [comment]
I see, yeah that's true. We should be restarting whenever the file changes.

**Comment by jmervine** [comment]
I would say the solution is to restart the server, or just ignore the cache buster in development.

**Comment by XhmikosR** [comment]
I don't see why cache buster matters but if you have something that works when editing main.js or style.css without restarting the whole process let me know.

**Comment by jmervine** [comment]
I don't, and my point was that the cache buster doesn't matter. I, out of habit, `shift-refresh` after editing. In which case, neither cache headers or cache buster prevent the changes from being seen.

**Comment by XhmikosR** [comment]
I know that too. Like I said I was trying to see what is causing the
failures with SRI ND at that point I thought it was caching.

**Comment by XhmikosR** [comment]
Closing this for now since by inlining our assets we no longer hit the issue.
