### ISSUE TITLE
Set `X-Frame-Options`, `X-XSS-Protection` for HTML files only

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#743]
Also, cache HTML files only with max-age=3600. I noticed that currently we set those headers for xml files too, like sitemap.xml.

**Comment by ScottHelme** [comment]
It might be worth nothing that both of these features can be enabled in CSP instead/also.

https://scotthelme.co.uk/csp-cheat-sheet/#frame-ancestors

https://scotthelme.co.uk/csp-cheat-sheet/#reflected-xss

**Comment by XhmikosR** [comment]
Thanks! I admit, I have never used those 2 directives with any CSP implementation I have done.

That being said, can you submit this info to HTML5 boileplate server configs so that everyone benefits from it?
