### ISSUE TITLE
Hangs forever in Safari over HTTPS

### ISSUE THREAD

**Issue by edc** [MaxCDN/bootstrap-cdn#765]
When accessing https://maxcdn.bootstrapcdn.com or anything under that hostname in Safari, it loads for ever. This has broken a lot of sites. Reproducible on ~~both~~ desktop ~~and mobile~~ Safari. It works fine with HTTP.

**Comment by jmervine** [comment]
@edc Mind giving some full path examples, as `https://maxcdn.bootstrapcdn.com` shouldn't load anything.

This domain is for assets only, e.g.

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

... which I verified on Safari [Version 9.1.2 (11601.7.7)]

**Comment by jmervine** [comment]
@jdorfman As a followup, we might consider redirect maxcdn.bootstrapcdn.com 404s to www.bootstrapcdn.com?

**Comment by edc** [comment]
@jmervine that's interesting. On my Safari 9.1.2, both the asset link you mentioned and https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js hang for ever. But they load instantly on Chrome.

**Comment by edc** [comment]
Actually, I think it's probably just my machine. My VM with the same version of Safari works OK. Closing.

**Comment by tophattom** [comment]
@edc Did you figure out what was the cause of the problem? I'm having the same issue with Safari

**Comment by jdorfman** [comment]
@jmervine maybe just redirect `maxcdn.bootstrapcdn.com/` to `www`?
@tophattom are you running a VM?
