### ISSUE TITLE
Different number of tests on Windows 

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#766]
So, while setting up AppVeyor I noticed that on Windows the same command `node make travis`, runs 1840 tests instead of 3153 tests on Travis.

/CC @jmervine for any ideas

**Comment by jmervine** [comment]
@XhmikosR How many tests are run for you locally when you run `node make travis`?

**Comment by XhmikosR** [comment]
The same as AppVeyor.

**Comment by jmervine** [comment]
Okay, so locally I'm getting `3161 passing (4m)`. Still digging.

**Comment by jmervine** [comment]
Installed a windows vm, node and git.

This block isn't working on windows... https://github.com/MaxCDN/bootstrap-cdn/blob/develop/tests/functional_test.js#L217-L235

**Comment by jmervine** [comment]
Still debugging.

**Comment by XhmikosR** [comment]
Might be `fs-walk` then.
