### ISSUE TITLE
Revive WordPress Plugin

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#778]
Our [WordPress plugin](https://wordpress.org/plugins/bootstrapcdn/) hasn't been updated in 2 years. This is because we could just update a JSON file on the origin and not have to make any commits to the plugin. That ends today. From now on @petarpetrovic will be taking charge and updating the plugin any time Bootstrap or Font Awesome updates.

Tasks (@petarpetrovic):
- [ ] Semver bump to `1.0.0`
- [ ] Update plugin to pull from local `json` file
  - [ ] Update Bootstrap version numbers (including 4-alpha releases)
  - [ ] Update Font Awesome version numbers (including)
- [ ] Update branding to StackPath
- [ ] Update readme (e.g. remove "Auto-update to latest Bootstrap version")

Other tasks (blockers)
- [x] @jimaek add `petarpetrovic` as a WordPress Plugin author
- [ ] talk to @jmervine about adding the plugin to the repo (or create new one)

**Comment by jdorfman** [comment]
Welcome to the team @petarpetrovic 🤘

**Comment by jimaek** [comment]
petarpetrovic now has commit abilities. To change the authors you need to edit a file in the repo https://plugins.svn.wordpress.org/bootstrapcdn/trunk/readme.txt

**Comment by jdorfman** [comment]
@petarpetrovic any interest? If not I'll close it.

**Comment by petarpetrovic** [comment]
@jdorfman I've started working on this a couple of months ago but had to make a month long hiatus because stuff, but anyway, this shouldn't be closed for the time being.

**Comment by jdorfman** [comment]
@petarpetrovic I feel you. If you want to take another stab, just let me know. No pressure either way.

**Comment by petarpetrovic** [comment]
@jdorfman I'll continue working on this in a few days for sure, no worries.
