### ISSUE TITLE
Certificate Revoked

### ISSUE THREAD

**Issue by nbrink91** [MaxCDN/bootstrap-cdn#779]
We are using the following CDN and the certificate appears to be revoked.

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
![screen shot 2016-10-13 at 8 30 02 am](https://cloud.githubusercontent.com/assets/19517049/19349095/453e4058-911f-11e6-9081-682388c878ef.png)

**Comment by skorokithakis** [comment]
We're seeing this too. What's going on?

**Comment by nbrink91** [comment]
It appears that it is a GlobalSign issue.

https://www.globalsign.com/en/status/

https://twitter.com/globalsign/status/786505261842247680

**Comment by jdorfman** [comment]
Sorry forgot to mark this as a duplicate #780 (even though this was opened first =/). This issue has been resolved. 

As @nbrink91 mentioned, it was a GlobalSign issue. Here is the whole story:
www.theregister.co.uk/2016/10/13/globalsigned_off/

If you run into any more issues please email support@maxcdn.com and they will look into & fix it faster than I can.
