### ISSUE TITLE
http:// Access to v3.3.7 CSS "Cannot Be Reached"

### ISSUE THREAD

**Issue by geoffhumphrey** [MaxCDN/bootstrap-cdn#780]
The http:// (non SSL) access to the v3.3.7 CSS file is not available. 
http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

https:// (SSL) access is available:
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

This is breaking a number of sites that utilizing the open source software I develop. Any thoughts on a cause?

This is limited to ONLY the Bootstrap 3.3.7 CSS file. 3.3.6, etc. all function properly using either protocol.

**Comment by jdorfman** [comment]
@geoffhumphrey can you do the following:

* `curl -I http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`
* Paste the output of http://debug-17.netdna-cdn.com/

**Comment by geoffhumphrey** [comment]
@jdorfman, forgive me. I'm not familiar at all with cURL. Apologies. However, I have determined that it seems limited to Chrome on Windows (latest version - 54.0.2840.59).

Tested:
- Firefox 45.1.0 (Win), 45.3.0 (Mac), 5.0 (iOS)
- Chrome 54.0.2840.59 (Win and Mac), 53.0.2785.109 (iOS)
- Safari 10 (Mac and iOS)

**Comment by jdorfman** [comment]
@geoffhumphrey Can you give me a url of a site this is happening on?

Better yet email: support@maxcdn.com they will get it fixed faster than I can

**Comment by geoffhumphrey** [comment]
Thanks @jdorfman. I will email them directly.

I can't replicate the problem on any other machine (Win/Mac) or browser other than Chrome on a certain machine, it's something local on my end that I haven't figured out yet. Weirdness. Hope I didn't waste your time. Thank you for your help.

**Comment by jdorfman** [comment]
@geoffhumphrey Didn't waste my time at all, they are just a lot better of figuring this out than me ;)
