### ISSUE TITLE
Add Bootstrap Material Design

### ISSUE THREAD

**Issue by theel0ja** [MaxCDN/bootstrap-cdn#786]
Please add [Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design) to BootstrapCDN.

**Comment by jdorfman** [comment]
@theel0ja this looks interesting. I will talk it over with @jmervine and @XhmikosR 

In the meantime I highly recommend JSDelivr (they use our network): http://www.jsdelivr.com/projects/bootstrap.material-design

**Comment by XhmikosR** [comment]
I don't think it makes sense. I mean, then everyone would like to add another Bootstrap theme and so on.

**Comment by XhmikosR** [comment]
So, what should we do with this?

**Comment by jmervine** [comment]
@jdorfman I'll leave it to you, but thinking this might be better for JSDelivr, as you said. That said, I'm always down to expand our footprint where it makes sense., so I'll leave it up to you.

**Comment by jdorfman** [comment]
unpkg.com is hosting it which is better since the Bootstrap Material Design team doesn't have to wait for us to upload it.

![image](https://user-images.githubusercontent.com/398230/33232206-aedf73aa-d1b6-11e7-8896-9912384344ef.png)
