### ISSUE TITLE
Chrome HTTPS / SSL issue: ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

### ISSUE THREAD

**Issue by gdubya** [MaxCDN/bootstrap-cdn#789]
Similar to #146, it looks as though the security certificates have expired again.

**Comment by wdoekes** [comment]
I don't think it has expired. But my Chrome reports that the Certificate Transparency check fails:

https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js
```
Attackers might be trying to steal your information from maxcdn.bootstrapcdn.com (for example, passwords, messages, or credit cards). NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED
```

Possibly related:
https://sslmate.com/blog/post/ct_redaction_in_chrome_53

**Comment by gdubya** [comment]
oh, I didn't read the certificate details properly. Yes, you are correct. It has not expired. I will update the issue title.

**Comment by gdubya** [comment]
Certs are fine according to Firefox 49.0.2

**Comment by gdubya** [comment]
This appears to be a Chrome issue, so i'll close this issue.

(e.g. https://meetup.com also appears to be affected)

**Comment by chren-de-large** [comment]
Experienced same issue with our app on Mint & Chromium 53
