### ISSUE TITLE
Replace MaxCDN icon and link

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#820]
We need to replace the MaxCDN "M" with the StackPath icon: https://cl.ly/471q371k282N and the URL to: https://www.stackpath.com/

![image](https://cloud.githubusercontent.com/assets/398230/21242403/17019970-c2c9-11e6-87b3-3ca229542e04.png)

Future updates will be replacing all MaxCDN branding/links. Thanks!

**Comment by XhmikosR** [comment]
I'll have a look later when I'm back or tomorrow.

Thy means that we won't need font awesome or we will need 1. I'll see if we
can get rid of it later.
