### ISSUE TITLE
Bootstrap CDN SSL error on Chrome

### ISSUE THREAD

**Issue by touqeer-wal** [MaxCDN/bootstrap-cdn#843]
I'm getting Privacy error `Your connection is not private` on Google Chrome version `54.0.2840.100` on Ubuntu 16 attached is the screenshot:
[https://s29.postimg.org/5o3jd1tuv/Screenshot_from_2017_01_19_12_58_26.png](https://s29.postimg.org/5o3jd1tuv/Screenshot_from_2017_01_19_12_58_26.png)

I've also tried to upgrade my Chrome version but the issue still exist's.

If you need more details let me know.

**Comment by jdorfman** [comment]
@touqeer-wal checking it out

**Comment by jdorfman** [comment]
Update from support: 
* "probably another Chrome issue"
* "I have Ubuntu running in a VM so I'll try to replicate"

**Comment by petarpetrovic** [comment]
Hi @touqeer-wal, I was not able to replicate the issue on my end. That being said, I'll need some additional stuff from you:

1) are you able to replicate this only in Chrome or in other web browsers as well?
2) have you tried flushing the local CRL/OCSP cache along with Chrome cache and then reloading the URI in question? You can flush local CRL cache with `$ dirmngr --flush`
3) if you still get the same error message after 2), I will need you to perform a traceroute towards maxcdn.bootstrapcdn.com URI and paste the output here

Please keep us posted, thanks!

**Comment by touqeer-wal** [comment]
@petarpetrovic i think it was only a Chrome issue, because i cannot replicate this on FireFox yesterday.
Yesterday i've cleared Chrome Cache several times and also restarted my machine but the issue persist.

Today i'm not getting the issue on chrome so think it's fixed, i didn't do any thing from my end.

Here is the `traceroute` which you needed:

```
touqeer@tshafi:~$ traceroute maxcdn.bootstrapcdn.com
traceroute to maxcdn.bootstrapcdn.com (198.232.125.123), 30 hops max, 60 byte packets
 1  10.10.14.1 (10.10.14.1)  1.225 ms  1.478 ms  1.586 ms
 2  10.10.12.3 (10.10.12.3)  0.889 ms  0.898 ms  0.884 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

If you need more info on this from me please let me know.

Thanks!
