### ISSUE TITLE
Bootlint for BS4-alpha

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#846]
@jdorfman We'll need to discuss the best way to handle delivering https://github.com/twbs/bootlint/issues/304 (also see [here](https://github.com/twbs/bootlint/issues/396) for context) -- if at all -- while BS4 is still in alpha.

**Comment by jdorfman** [comment]
When BS4 is out of alpha we will host the updated Bootlint(er). I don't think there will one for the alpha. Maybe for the RC's but either way we will host whatever they release.

**Comment by jmervine** [comment]
Maybe I'm miss reading https://github.com/twbs/bootlint/issues/396, but it kind of sounds like there might be.

**Comment by Herst** [comment]
Now it's the beta.

**Comment by XhmikosR** [comment]
This issue is for Bootlint, not Bootstrap. Bootlint doesn't work with v4 yet.

**Comment by Herst** [comment]
@XhmikosR But the title said _"BS4-alpha"_, also @jdorfman talked about _"when BS4 is out of alpha"._
