### ISSUE TITLE
Duplicate requests and differing Referrer Policies

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#854]
Investigate and respond to the following report...

Source: https://www.reddit.com/r/webdev/comments/6mduuk/bootstrap_cdn_integrity_inlcude/

---
I change my CDN links (Bootstrap/FontAwesome/JQuery) to have the recommended integrity attribute.

```
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```

Today I looked at my Network tab and saw that it duplicates the requests for Bootstrap and FontAwesome, just the Referrer Policy is different.

One is unsafe-url and the other is the common no-referrer-when-downgrade

---

**Comment by jmervine** [comment]
Looking at a project that uses both https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css and https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js with SRI, I am seeing a duplicate of bootstrap.min.css, however, notice in the screenshot that one is labeled "(from disk cache)".

<img width="1691" alt="screen shot 2017-07-14 at 9 34 51 am" src="https://user-images.githubusercontent.com/837893/28221333-c1661568-6877-11e7-8197-802b29cbe8de.png">


Browser information:

```
Google Chrome
Version 59.0.3071.115 (Official Build) (64-bit)
```

**Comment by jmervine** [comment]
When running this in Firefox I'm only seeing a single reference...

<img width="1758" alt="screen shot 2017-07-14 at 9 42 52 am" src="https://user-images.githubusercontent.com/837893/28221629-e58bee08-6878-11e7-96d8-407e9053fc37.png">


Browser information:

```
Firefox (Mac OS)
54.0.1 (64-bit)
```

**Comment by XhmikosR** [comment]
Like we discussed on Slack, I can't see something wrong on our side from a quick look. I mean, we don't even set `no-referrer-when-downgrade` ourselves. It must be something the browsers do when the devtools is open. I can't think of any other reason myself...

**Comment by jdorfman** [comment]
via @jonathanKingston on Twitter:

```
Sounds like Chrome is running an experiment to see if they can make that the default for unsafe requests?
```

- https://twitter.com/KingstonTime/status/885926332047163393

**Comment by qerim** [comment]
I have the same issue (only in Chrome). The CSS files are fetched twice.

**Browser**: Chrome 59.0.3071.115 (Official Build) (64-bit)
**OS**: Windows 10 x64
**URL**: [https://jahdaut.com](https://jahdaut.com)

![image](https://user-images.githubusercontent.com/3625009/28250596-8a55c386-6a64-11e7-8200-25cbac09609f.png)

**Comment by XhmikosR** [comment]
I think we can close this. It's something browsers do and not related to us.
