### ISSUE TITLE
Display Ads that support Open Source 

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#861]
A conversation with @piamancini

> We've been talking to CarbonAds about the [thread we started on twitter](https://twitter.com/_prateekbh/status/881806838253146112) and we are running a test with the people who showed interest in the survey.

> We've created an ad code for https://www.bootstrapcdn.com/ and the monthly payouts will go to the Open Source Collective. The script  you need to include is: 

```html
<script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?zoneid=1673&serve=C6AILKT&placement=bootstrapcdncom" id="_carbonads_js"></script>
```

> Please keep in mind that it is possible for the styling of the ad to inherit other styles from your site, and you may need to add some additional styles to make it look perfect .Let me know if you want an ad placement suggestion for your site with some CSS. 

* [Display Networks - FAQ - Publishers](https://www.evernote.com/shard/s456/sh/1b37bdf5-937f-4b8e-a480-d3bdef146b7d/19f65f820e274f6234149eb7ce105dad)
* [Carbon Ad Style Guide](https://www.evernote.com/shard/s456/sh/62b7c21b-fd20-46f7-84ec-80f9b5a0892e/81cfa6e35a6cbc6c6f9af47c19d874a7)

@jdorfman's Todos:

- [x] Talk to James L at StackPath
- [x] Create PR for @XhmikosR #862 
- [ ] Follow up with Pia

**Comment by XhmikosR** [comment]
Where do you want to place it in the layout?

**Comment by jdorfman** [comment]
@XhmikosR not sure yet. I need to talk to James first before _anything_ starts. I'll let you know after we chat.

**Comment by piamancini** [comment]
hey! regarding placement, if it's helpful for the conversation: carbon ads sent this suggestion for bootstrapcdn.com - https://s.codepen.io/carbonads/debug/EXBdGO
with this css https://codepen.io/carbonads/pen/EXBdGO
hope it helps!

**Comment by jmervine** [comment]
I'm cool with that placement, I might want to add a little padding to the top to drop it down a bit. Something like:

<img width="1568" alt="ss" src="https://user-images.githubusercontent.com/837893/28472918-70487696-6df7-11e7-8e58-eb9df51980dc.png">

That said, I'll leave it up to @jdorfman, as I don't feel that strongly about it. ;)

**Comment by XhmikosR** [comment]
If someone makes a PR I will definitely be able to have a look. I feel like the new div should be inside the row in a separate column.

Also, I suppose you know that where you placed it, the ad will only be visible on large screens.

**Comment by XhmikosR** [comment]
The carbonads script should be in the footer too. Also, I wonder, isn't it possible to use a class to target the div instead of an ID? My guess would be it's possible because since IDs are unique, you won't be able to target many ads in the same page.

**Comment by jdorfman** [comment]
I have a call with James at StackPath this afternoon. I will update this issues asap.

**Comment by XhmikosR** [comment]
So, ideally if we are not going to show the ads on small screens, I'd go with a pure JS solution which would skip even loading the script. Should be pretty easy to implement. My main concern is to handle the `resize` event but we can discuss this in detail when we have a PR.

**Comment by XhmikosR** [comment]
About the ID comment I made above, I read [here](https://www.evernote.com/shard/s456/sh/62b7c21b-fd20-46f7-84ec-80f9b5a0892e/81cfa6e35a6cbc6c6f9af47c19d874a7) that it requires only one ad per page hence the ID usage.

**Comment by XhmikosR** [comment]
Since I don't have access to the dashboard and I don't have any Carbon Ads account myself, I can only assume that the script's position is what their dashboard gives you by default. Now, I can't believe one isn't able to customize this, so my guess is we'll need to go the other way with placing a `div` with an `id` and loading the scripts ourselves, similarly to what we do with the Twitterdeck script.

But I also see that they require the ads show up on mobile so the position the mockup has the ad in, won't do the job.

**Comment by piamancini** [comment]
They provide this [style guide]( https://www.evernote.com/shard/s456/sh/62b7c21b-fd20-46f7-84ec-80f9b5a0892e/81cfa6e35a6cbc6c6f9af47c19d874a7)

and the dashboard also says: 
Ad Code Style Guide
We want Carbon Ads to integrate seamlessly into your website. Ads should be displayed above the fold (top 800 pixels) on all pages of your site. Here's what the final markup will look like for the ads: 

https://app.carbonads.net/static/images/carbon-tags.gif

**Comment by jdorfman** [comment]
Just talked to James and got the ok. @piamancini I will continue this via email.

**Comment by jdorfman** [comment]
@XhmikosR do you want me to make a separate issue for this?

**Comment by XhmikosR** [comment]
Separate issue, no, a pull request would be nice to have in order to get
things started :)

**Comment by XhmikosR** [comment]
Everyone interested: please check the current branch https://bootstrapcdn-dev-pr-862.herokuapp.com/

1. I can't find any info how to initialize carbonads manually with a plain `document.createElement` way. If anyone has info on this let me know
2. I'm still seeing CSP errors randomly so I'm not sure if carbonads follow a scheme for their resources which we could whitelist further. So this means some ads might not show right (no image)
4. I don't really like the modal approach. Maybe a tooltip might be better, but I'm not sure if it will work on mobile
5. I'm not a lawyer but I'm pretty sure there should be a privacy policy or something especially now with the ads

**Comment by jdorfman** [comment]
I'll have more feedback tomorrow but the modal looks great on mobile. https://photos.app.goo.gl/mmYAg0kJ0aOaNumA3

Good point about privacy policy. I'll look into that asap. 

Thanks!

**Comment by XhmikosR** [comment]
An alternative way would be to use a popover.

**Comment by XhmikosR** [comment]
I switched to a popover. Let me know which one you all prefer.

**Comment by piamancini** [comment]
@XhmikosR from the carbon team on the ID comment reference: 
 
You can use the JavaScript to skip loading the ad on the mobile. 
Something like this should suffice:
```<script>
 if (document.documentElement.clientWidth > 870) {
   document.write('<script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?zoneid=2000&serve=C6AILKT&placement=carboncom" id="_carbonads_js"><\/script>');
 }
</script>```

On the CSP errors: 
You can fix the CSP errors by whitelisting the following domains:
```convertro.com
c3tag.com```

Also: 
These image pixels are used by quality advertisers like Slack, Microsoft, and Squarespace to have a unified report across all the ad platforms they run. Their purpose is to help the marketer at these companies to keep track of their campaign performance in a single location.

We know pixels can be a sensitive issue for developers due to "retargeting" where advertisers can serve similar ads by following site users' trace. These are not retargeting pixels, and only provide means to track the impressions, clicks, and conversions for each campaign.

**Comment by sayzlim** [comment]
> But I also see that they require the ads to show up on mobile too so the position the mockup has the ad in, won't do the job.

@XhmikosR, I’m from Carbon Ads. The ad on mobile is optional. You can skip loading the ad with a JavaScript. Something like this should suffice:

```
<script>
 if (document.documentElement.clientWidth > 870) {
   document.write('<script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?zoneid=2000&serve=C6AILKT&placement=carboncom" id="_carbonads_js"><\/script>');
 }
</script>
```

---

> I'm still seeing CSP errors randomly so I'm not sure if carbonads follow a scheme for their resources which we could whitelist further. So this means some ads might not show right (no image)

You can fix the CSP errors by whitelisting the following domains:

```
convertro.com
c3tag.com
```

These image pixels are used by quality advertisers like Slack, Microsoft, and Squarespace to have a unified report across all the ad platforms they run. Their purpose is to help the marketer at these companies to keep track of their campaign performance in a single location.

We know pixels can be a sensitive issue for developers due to "retargeting" where advertisers can serve similar ads by following site users' trace. These are not retargeting pixels, and only provide means to track the impressions, clicks, and conversions for each campaign.

**Comment by jdorfman** [comment]
@sayzlim thanks for the help! I want to start at the bottom and adjust if needed. I do want the ad to perform well, I just feel more comfortable starting in the current position for now.

**Comment by jdorfman** [comment]
@sayzlim any ideas regarding the privacy policy?

**Comment by sayzlim** [comment]
@jdorfman I’ll discuss this with the team. Will keep you updated soon.

**Comment by sayzlim** [comment]
@jdorfman you should be able to use our copy of privacy policy at https://carbonads.net/privacy.php. Check the details and remove anything that doesn’t apply to your site usage. Some publishers choose to create a basic privacy policy with generator at http://getterms.io/

**Comment by jdorfman** [comment]
@sayzlim that is perfect! 

@XhmikosR I will work on the markdown formatting and make another PR. We will just link to the markdown file on github from bootstrapcdn.com.

https://gist.github.com/jdorfman/4efa9f1d6a856cb99f96e01d23182af5

**Comment by XhmikosR** [comment]
@sayzlim: unfortunately, I still see CSP errors. I see resources from more origins than the ones you mentioned above like `s0.2mdn.net` and `ad.doubleclick.net`. No idea if they are more and we can't do this all the time; we need a clear source of origins we can whitelist.

**Comment by jdorfman** [comment]
@XhmikosR where are you seeing the errors? The console is clean on https://bootstrapcdn-dev-pr-862.herokuapp.com/

![image](https://user-images.githubusercontent.com/398230/28705402-72777df4-7324-11e7-8d0c-98d4cd7feb6d.png)

**Comment by XhmikosR** [comment]
You are looking at one time ads @jdorfman. I test locally and ads change hence I'm able to see the errors. I can also see the reports in report-uri.io.

**Comment by jdorfman** [comment]
@XhmikosR can you share the report-uri.io report for @sayzlim please

**Comment by XhmikosR** [comment]
Nope, it would be useless because there are many other results that would confuse him.

I even see a script attempt to `http://adn.fusionads.net/launchbit/9533/developers/...`.

**Comment by jdorfman** [comment]
@XhmikosR check slack

**Comment by XhmikosR** [comment]
My main concern is the script source. I definitely won't whitelist `adn.fusionads.net` unless we have a clear explanation why carbonads script even tries to load that.

Note that this is not just me being anal; this is security and the power of CSP. :)

**Comment by XhmikosR** [comment]
My current CSP changes are https://github.com/MaxCDN/bootstrap-cdn/pull/862/commits/09a50d579d1701e55e745b7d415ec0a434c7c23a The top ones are the script ones, down the images.

**Comment by jdorfman** [comment]
Fusion = Carbon = BuySellAds

```bash
$ dig +short adn.fusionads.net
fusionlegacy.bsa.netdna-cdn.com.
```

BSA = BuySellAds which owns both entities.

**Comment by XhmikosR** [comment]
Thanks.

Still, the CSP errors continue. It's pretty clear that the sources @sayzlim mentioned above are very incomplete. And I wonder if all this makes any sense. If a new ad is added, it could still break. We can't keep doing this. There must be a clear list of sources one can whitelist for images in order for the ads to work.

**Comment by sayzlim** [comment]
@XhmikosR so far we haven’t seen any domains that need to be whitelisted except the one you added in the referenced commit. Only few advertisers will insert the image pixel, and most of them are using the one you added before. Thanks for pushing the ad live! @jdorfman

**Comment by XhmikosR** [comment]
@sayzlim: the final list is this: https://github.com/MaxCDN/bootstrap-cdn/commit/91818dbc160527cfac5b815214b453e3d59489fe

Pretty inconsistent IMO.
