### ISSUE TITLE
Remove twitter from boostrap path

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#867]
At least for v4. Personally I'd remove it from everywhere but I'm not familiar how things work with S3.

/CC @jmervine @jdorfman

**Comment by jmervine** [comment]
@jdorfman can we check the cdn and see if anyone is even hitting that?

**Comment by XhmikosR** [comment]
Any news about this?

**Comment by jmervine** [comment]
@jdorfman ^^

**Comment by jdorfman** [comment]
We don't need to advertise it, but not going to remove it. Even if it is 1 hit a year, I still want that legacy use case to work.

**Comment by XhmikosR** [comment]
And why can't you redirect the old path?

**Comment by jdorfman** [comment]
S3 doesn't support symlinks. They do have a hack but it makes the http request 301 which is unacceptable.

https://stackoverflow.com/a/29462540/1258484

**Comment by jdorfman** [comment]
@jmervine can we just adjust the tests to ignore `https://maxcdn.bootstrapcdn.com/twitter-bootstrap/*` starting at `4.0.0-beta.*` please?
