### ISSUE TITLE
Remove Snyk Badge from README

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#869]
There is a [node package](https://www.npmjs.com/package/shelljs) that we depend on for dev that doesn't have a fix making the badge show:

![image](https://user-images.githubusercontent.com/398230/31184645-d4e81bd4-a8de-11e7-8da7-9eee9c5b5e48.png)

This might alarm those who don't have our knowledge on the issue:

![image](https://user-images.githubusercontent.com/398230/31184769-2e725a8e-a8df-11e7-8aca-9698864761c8.png)

**Comment by jmervine** [comment]
👍🏽

**Comment by XhmikosR** [comment]
It's your call, guys, I don't really have an opinion :)
