### ISSUE TITLE
Update SSL cert

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#870]
The cert for `www` expires Oct 13 2017. Action Items:

- [ ] Buy new cert @jdorfman
- [ ] Upload it to  Heroku @jmervine 
- [ ] Consult Alex @ StackPath once complete

**Comment by jmervine** [comment]
@jdorfman Pretty sure we can do this through Heroku now for free. Let me do some digging today and I'll update this issue with my findings.

**Comment by jdorfman** [comment]
You rock

**Comment by alexmatic** [comment]
@jmervine  let me know if you need anyhting from my end.

**Comment by jdorfman** [comment]
cc @alexmatic

**Comment by jmervine** [comment]
@alexmatic We're going to need to update CNAMEs to get ACM working, see https://devcenter.heroku.com/articles/automated-certificate-management. I'll ping you slack.

**Comment by jdorfman** [comment]
Thanks @jmervine 

![image](https://user-images.githubusercontent.com/398230/31240018-f99852c0-a9b3-11e7-8d9d-182b15e4b690.png)

Going to close this out.
