### ISSUE TITLE
Stop testing twitter-bootstrap uri after 2.3.2

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#877]
Anything after `2.3.2` should not be tested with `twitter-bootstrap` in the url

e.g.: https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css

This will speed up test as well as taking care of #867

**Comment by jdorfman** [comment]
@jmervine is this hard to do?

**Comment by jmervine** [comment]
Probably not, I'll look in to it real quick.
