### ISSUE TITLE
Add new bootswatch themes

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#881]
Now [supports Beta-4](https://bootswatch.com/)

Request: https://twitter.com/intranix/status/929013966289940480

**Comment by jdorfman** [comment]
Todo: create issue to upgrade to `4-beta` and Bootswatch theme on `www`

**Comment by jmervine** [comment]
<img width="1273" alt="screen shot 2017-11-22 at 9 08 12 am" src="https://user-images.githubusercontent.com/837893/33140392-b277e5fa-cf64-11e7-8e3e-c391d6f34be8.png">

@jdorfman Thinking something like this for the header.

**Comment by jmervine** [comment]
<img width="1333" alt="screen shot 2017-11-22 at 9 09 44 am" src="https://user-images.githubusercontent.com/837893/33140464-e676e69e-cf64-11e7-9a72-468b1a9f1780.png">

Or this....

**Comment by jdorfman** [comment]
Thinking:
```
Beta 4
├── Bootstrap
└── Bootswatch
```

Also synced S3

**Comment by jdorfman** [comment]
@jmervine check 86e7da8499cd3f1ea0eaa99678a1aa6804032b3a
