### ISSUE TITLE
Disable Query String (Treat as separate cacheable item) option in MaxCDN

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#888]
Last month our cache hit percentage was `99.57% (68,789,568,942)`

Making our non-cache hits `0.43%` or `297,179,793` requests going back to S3.

![image](https://user-images.githubusercontent.com/398230/33274437-e9fc05b8-d344-11e7-8710-fb6111a3f1b3.png)

This will prevent requests like this going back to S3:
`GET /bootstrap-cdn/public/font-awesome/4.7.0/css/font-awesome.min.css?refresh=226?refresh=298?refresh=395?refresh=478?refresh=568?refresh=658?refresh=740?refresh=823?refresh=897...`

@petarpetrovic will be tailing the edge logs for any possible issues.

Steps:
- [x] Disable option
- [x] Purge Cache
- [x] Tail CDN/edge logs
- [x] Monitor Twitter
- [x] Check S3 Logs
- [x] Examine S3 Billing

**Comment by petarpetrovic** [comment]
I confirm the change didn't affect the CDN delivery on any edge location. The assets have been cached successfully after the purge.

**Comment by jdorfman** [comment]
Twitter looks good

**Comment by jdorfman** [comment]
We still need more data but so far it is looking good:

![image](https://user-images.githubusercontent.com/398230/33387721-e03e4dfc-d4e2-11e7-924e-dbba06308ab0.png)

Comparing Yesterday (Tue. 11-28-2017) to last Tue (11-21-2017) there is a `90.78%` decrease in cost.

**Comment by jdorfman** [comment]
Looks good. Closing.
