### ISSUE TITLE
[Security] XSS in respond-proxy.html

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#944]
Reported on Twitter: https://twitter.com/isecator/status/945402519337013249

`http://netdna.bootstrapcdn.com/respond-proxy.html?url=javascript:alert()&css=data%3A%2C`

Suggestions on how to move forward.

**Comment by XhmikosR** [comment]
I'd just remove the file and the CNAME like I told you the other day.

This  file is from html5shim.

**Comment by jdorfman** [comment]
@XhmikosR but if someone is using it, it would break their site, right?

What if we just update it with `https://s.yimg.com/lm/ysbp/htmlrespond-proxy.html`?

Looks like it is fixed: https://s.yimg.com/lm/ysbp/htmlrespond-proxy.html?url=javascript:alert()&css=data%3A%2C

**Comment by XhmikosR** [comment]
If one is using IE < 9, not sure this really matters...

**Comment by jdorfman** [comment]
**I didn't find anything in the logs:** 
![image](https://user-images.githubusercontent.com/398230/34388495-c104a3d4-eae8-11e7-9151-0fb4a1ad9ad8.png)


**At the same time, IE 8 is still being used somewhat:**
![image](https://user-images.githubusercontent.com/398230/34388399-31b4fc24-eae8-11e7-8d0a-f41a5a67d547.png)

via: https://blog.pendo.io/2016/01/14/analysis-of-browser-usermarket-share-or-so-long-ie8-9-and-10/

I vote update `respond-proxy.html`. @jmervine your 2¢?

**Comment by XhmikosR** [comment]
What you show above is from Oct-Dec 2015, not 2017.

**Comment by XhmikosR** [comment]
https://www.w3counter.com/globalstats.php?year=2017&month=11
https://www.w3counter.com/trends

**Comment by jdorfman** [comment]
I was comparing 2015 to **Past Week**

While IE 8 dropped ~15% in 2 years, it is still ~5% in 2017

**Comment by XhmikosR** [comment]
Well, maybe in China. I don't see this being an issue and I'd just remove it.

**But** if you are going to replace the file, you should check with the upstream project. It doesn't make any sense for us to use custom files and stop being in sync with upstream.

**Comment by jmervine** [comment]
+1 on removing it.

**Comment by jdorfman** [comment]
K I'll create a PR and remove from S3

**Comment by jdorfman** [comment]
done

```
> icurl "http://netdna.bootstrapcdn.com/respond-proxy.html"
HTTP/1.1 403 Forbidden
Date: Wed, 27 Dec 2017 18:15:48 GMT
```
