### ISSUE TITLE
Clean up tweets / reduce the number of visible ones

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrap-cdn#953]
1. I'd say just remove the simple ones which are like "Thank you"
2. See if there's a way to reduce the number of visible tweets

**Comment by jdorfman** [comment]
- [ ] 1
- [ ] 2

**Comment by jdorfman** [comment]
@XhmikosR we need to fix (or remove) the OG image. The "B" is cut off.

![image](https://user-images.githubusercontent.com/398230/34645054-191806b6-f2f9-11e7-8d96-7c0cf388b631.png)

**Comment by XhmikosR** [comment]
That I don't know, it's like that from day 1. In theory what we use now should be OK (a 256x256 image).

Did you reduce the number of the visible tweets?

**Comment by XhmikosR** [comment]
Because I'm still seeing more than 5.

**Comment by jdorfman** [comment]
Did you use the new code? There is a data-limit attribute.

**Comment by XhmikosR** [comment]
You shouldn't have closed the issue then. It's not implemented on the frontend...

I'll see how it looks because I think it will just look too tall.
